### ISSUE TITLE
2020/3/17 .NET 5 Preview 1 / VS 16.6 Preview 1

### ISSUE THREAD

**Issue by ufcpp-live** [ufcpp-live/UfcppLiveAgenda#1]
話しそうなこと:

- まあ、Preview **1** ですんで
- Visual Studio 16.5 の新機能、C# リファクタリング周りを中心に
- サイレントに C# 8.0 の NRT に修正が入ってる
- Async ValueTask Pooling
- .NET Conf "Focus on Xamarin"

参考リンク:

- https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-1/
- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.5.0
- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.6.0-pre.1.0
- https://github.com/ufcpp/UfcppSample/issues/287
- https://devblogs.microsoft.com/dotnet/async-valuetask-pooling-in-net-5/
- https://focus.dotnetconf.net/

**Comment by ufcpp-live** [comment]
https://youtu.be/a5Qs7u6CoqM

**Comment by ufcpp** [comment]
配信を終えたら閉じる運用でいいかな。
