### ISSUE TITLE
Visual Studio 16.8 Preview 2 / .NET 5.0 Preview 8

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#13]
- [Visual Studio 2019 v16.8 Preview 2 Releases New Features Today!](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-8-preview-2/)
  - .NET Productivity 周りをちょっと
- VS 16.8p1 の時に使えるようになってた C# 9.0 機能(module initializers, static anonymous functions, target-typed conditional expression)、[.NET 5.0 Preview 8](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-preview-8/)で dotnet コマンドでもコンパイルできるように
- C# 9.0 的には基本的にはバグ修正とかだけっぽいけども…
  - null 許容参照型とかはドキュメント更新なしで機能を merge してくるから怖い
    - unconstrained generic type parameter に対して `T?` って書けるようになってたり
        - `class C<T> { T? X() => default; }` がコンパイルできる
    - `DoesNotReturn` を付けてるのに `return` しちゃってるときに警告を出したり
  ‐ `record` に `static` 修飾は付けれないように

まあ、C# 的にはそんなに変更ないんで、短めで終わりたい。

**Comment by ufcpp** [comment]
この系統の配信にもシリーズタイトルみたいなのと再生リスト作りたいかも。

**Comment by ufcpp** [comment]
合わせて公開されたブログには↓もあるけども。

- [New C# Source Generator Samples](https://devblogs.microsoft.com/dotnet/new-c-source-generator-samples/)

「サンプルはサンプル」って感じのものなのでなんとも。
AdditionalFiles からのコード生成の例はこれが初めてかも。

**Comment by ufcpp-live** [comment]
本日のかき捨てコード

```cs
#nullable enable

using System;
using System.Diagnostics.CodeAnalysis;

var x1 = C<string>.M();
var x2 = C<string?>.M();
int x3 = C<int>.M();
Nullable<int> x4 = C<int?>.M();

//string | 0
// { x: x ∈ string } | { 0 }

// 0 = { }
// 1 = { 0 } = 1 ∩ { 0 }
// 2 = { 1, 0 } = 1 ∩ { 1 }
// 3 = { 2, 1, 0 } = 2 ∩ { 2 }

Console.WriteLine();

class C<T>
//where T :class // これがあれば前からOK
//where T :struct // これがあれば前からOK
// 制約なしは今回から初めてOK
{
    // これだとエラー。 
    // T? と言いつつ、C<int> とかを渡すと int。int? ではない
    //public static T? M() => null;

    // 実は nullable じゃなくて、defaultable
    // LINQ の FirstOrDefault 的な奴
    // あまりにきもいから、当初 T?? にしようという案もあった
    // ? になったのは、 x ?? y の ?? と区別つかなくて困ったかららしい
    public static T? M() => default;
}

class C
{
    [DoesNotReturn]
    public void M0()
    {
        throw new InvalidOperationException();
    }

    [DoesNotReturn]
    public void M1()
    {
        Environment.FailFast("");
    }

    [DoesNotReturn]
    public void M2()
    {
        while (true) ;
    }

    [DoesNotReturn]
    public void M3()
    {
        M3();
    }
}
````

**Comment by ufcpp** [comment]
https://youtu.be/Uc04x0eZBBM
