### ISSUE TITLE
Visual Studio 16.8 Preview 3 / .NET 5.0 RC1

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#15]
ついにリリース候補に。

- [Announcing .NET 5.0 RC 1](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/)

VS の方は「Preview 3」。

- [Visual Studio 2019 version 16.8 Preview 3](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.8.0-pre-3.0)
  - GitHub サインインできるのよさそう
  - 後述の AnalysisLevel、IDE 内でもオプション設定できるようになってそう

Preview 2 からの C# 差分:

- [.NET 5 RC1 での C# 9.0](https://gist.github.com/ufcpp/57b193bd38342cf2b72e8da5fd51351b)
  - record に `==` オーバーロード、`ToString` オーバーライド追加
  - 関数ポインターが多少まともに (まだちょっと残タスクあり)
  - AnalysisLevel オプション(これまで warning waves って呼ばれてたやつ)追加

あと、Design Meeting Note 1件

- [C# Language Design Meeting for September 14th, 2020](https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-09-14.md)
  - C# 9.0 正式リリースまでに微調整程度はまだあるかも
    - `a?.b.c!.d.e` 問題とかは「可能な限り早くやる」とか言ってる

Source Generator がらみもちゃんと試しておきたかったものの…
Microsoft.CodeAnalysis.Analyzers パッケージを  nuget.org 上じゃなくて、

https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json

からでないと取れないバージョンに更新しないと動かなくなってる状態なのでまた今度。

**Comment by ufcpp-live** [comment]
配信中書き捨てコード1
ReferenceEquals (警告ウェーブ)で警告が出る条件

```cs
public static void MInt(int x, int y)
{
	ReferenceEquals(x, y); // 警告あり
}

public static void MValue<T>(T x, T y)
	where T : struct
{
	ReferenceEquals(x, y); // 警告あり
}

public static void MUnconstrained<T>(T x, T y)
{
	ReferenceEquals(x, y); // 警告なし
}
```

**Comment by ufcpp-live** [comment]
2
record の ToString の中身の仕様。
PrintMembers メソッドを介してる。

```cs
record Point(int X, int Y)
{
    // ToString の挙動をカスタマイズしたければこいつを上書き。
    // Point { 「この中の部分を Append」 }
    protected virtual bool PrintMembers(StringBuilder sb)
    {
        sb.Append("aaa");
        return true;
    }
}
```

**Comment by ufcpp-live** [comment]
3
C# 9.0 では直さない(たぶん直してる余裕ない)やつちょこっとあり。

```cs

record Base(int X);
record Derived : Base(0); // C# 9.0 時点では仕様

// C# 10.0 待ち…
//record Derived() : Base(0);

// 9.1 はないよなぁ…
// 7 時代、小数点リリースはなかなか大変だった…
//void m(int? x = default) { } // 7.1 のころ、0 扱い(本来は null。今は null)
```

**Comment by ufcpp-live** [comment]
4
もちろんリリースまでに治るやつもある。

```cs
record Point(int X, int Y);
record Point3D(int Z) : Point(1, 2); // Z のところに「未使用引数」警告
// C# 9.0 正式リリースまでには治る
```

https://github.com/dotnet/roslyn/issues/47142

**Comment by ufcpp-live** [comment]
https://youtu.be/VQLtwak8W0U

**Comment by ufcpp** [comment]
```cs
record Base(int X);
record Derived : Base(0); // C# 9.0 時点では仕様

// C# 9.0 正式リリースまでには以下の書き方はできるようになるはず。
//record Derived() : Base(0);
```
