### ISSUE TITLE
.NET 5.0 GA 記念雑談枠

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#19]
記念。

毎年恒例、ずっと Preview Channel な Visual Studio を使い続けているので正式リリース時点で何が新機能なのかわからなくなっている件。

改めてリリースノートとか、 [.NET Conf](https://www.dotnetconf.net/) に伴って公開されたブログに目を通していこうという配信。

- [Announcing .NET 5.0](https://devblogs.microsoft.com/dotnet/announcing-net-5-0/)
- [C# 9.0 on the record](https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/)
- [Visual Studio 2019 v16.8 and v16.9 Preview 1 Release Today](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-8/)
- [Announcing ASP.NET Core in .NET 5](https://devblogs.microsoft.com/aspnet/announcing-asp-net-core-in-net-5/)
- [Visual Studio 2019 16.8 リリースノート](https://docs.microsoft.com/ja-jp/visualstudio/releases/2019/release-notes#16.8.0)
- [Visual Studio 2019 18.9 Preview 1 リリースノート](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.9.0-pre-1.0)
- [.NET Conf 2019 - Day 1 ライブ配信](https://www.youtube.com/watch?v=mS6ykjdOVRg)

**Comment by ufcpp-live** [comment]
今日の書き捨てコード

「.NET 5 のパフォーマンス改善、かなりの割合 Hardware Intrinsics だよ」
「今、スピードを求めるなら言語がどうこうじゃなくて CPU のお気持ちをどのくらい察せられるかにかかってる」
「ただし、それをやるとCPUごとにすさまじい分岐が発生する」
「速いといわれてる C++ のライブラリは #ifdef だらけ」

```cs
// C++
#ifdef GCC
#ifdef AVX
#endif
#elif MSVC
#endif

if (System.Runtime.Intrinsics.X86.Avx.IsSupported)
{
}
else
{
}
```

**Comment by ufcpp-live** [comment]
record / target-typed new / タプルと匿名型 の不整合話

```cs
Point p1 = new Point { X = 1, Y = 2 };
Point p2 = new Point(1, 2);

Point p3 = new() { X = 1, Y = 2 };
Point p4 = new(1, 2);

var p5 = new { X = 1, Y = 2 };
var p6 = (1, 2);

record Point(int X = 0, int Y = 0);
```

今から1から言語を作るなら↓みたいになってたと思う。

```cs
Point p1 = Point { X = 1, Y = 2 };
Point p2 = Point(1, 2);

Point p3 = { X = 1, Y = 2 };
Point p4 = (1, 2);

var p5 = { X = 1, Y = 2 };
var p6 = (1, 2);
```

**Comment by ufcpp-live** [comment]
`{}` とか `()` とかの扱いは、default とか配列初期化子とかも絡む。

```cs
Point p1 = new(); // () 要る
Point p2 = default; // () 要らない
```

```cs
var array = new int[] { 1, 2, 3 }; // これは new int[]() {} とは書かず
int[] array = { 1, 2, 3 }; // C# 1.0 時代から有効なコード
var array = new object[] { 1, "" }; // 有効なコード
var array = new[] { 1, "" }; // 無効(要素からの配列型推論が効かない)
object[] array = { 1, "" }; // これは C# 1.0 時代から有効
```

**Comment by ufcpp-live** [comment]
https://youtu.be/i02HL8g-D1w

**Comment by ufcpp** [comment]
完全にテーマなく「雑談」で配信したときに、参加者が多いとほんとに脇道にそれて帰ってこれないという問題が…
