### ISSUE TITLE
Visual Studio Users Community Japan 勉強会 #6 質疑応答枠

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#21]
https://youtu.be/yDrQ2nCPfR8

今日の登壇の質疑応答雑談枠を今日立てるやつ。

その「今日の登壇」はこちら:

- [Visual Studio Users Community Japan 勉強会 #6](https://vsuc.connpass.com/event/192835/)
  - [YouTube 配信 URL: https://youtu.be/fSzksnRztIM](https://youtu.be/fSzksnRztIM)
  - [自分のスライド: C# 9.0 / .NET 5.0](https://www2.slideshare.net/ufcpp/c-90-net-50)

タイトル: C# 9.0/.NET 5.0
概要: C# 9.0/.NET 5.0 世代の大まかな流れと、C# 9.0の主要な機能を紹介します。

**Comment by ufcpp-live** [comment]
https://www.youtube.com/watch?v=7Gvr0d1vTQ4

**Comment by ufcpp-live** [comment]
インジェクションｗｗｗｗｗ

![image](https://user-images.githubusercontent.com/62176519/101238720-630c4c00-3725-11eb-9d60-938901b924e4.png)

**Comment by ufcpp-live** [comment]
```cs
m((A)9999); // こっちをエラーにしたい

int m(A b)
{
    return b switch
    {
        A.X => 1,
        A.Y => 2,
        A.Z => 3,
        _ => throw new Exception("来ないはずなのに…"),
    };
}

closed enum A
{
    X, Y, Z
}
```

**Comment by ufcpp-live** [comment]
```cs
#nullable enable

using System;
using System.Threading.Tasks;

var tcs = new TaskCompletionSource();
tcs.TrySetException(default(Exception)); // この行で例外

Task t = tcs.Task;

if (t.Exception != null)
{
    // 正常系
}

await tcs.Task; // ここで例外が出てほしかったのに、違う
```

**Comment by ufcpp-live** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world?tutorial-step=1 の今がどうなってるのか気になって、Environment.Version とかを表示。

```cs
Console.WriteLine(System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription);
Console.WriteLine(System.Environment.Version);
Console.WriteLine(System.Environment.OSVersion);
Console.WriteLine(System.Text.Encoding.Default);
Console.WriteLine(System.Globalization.CultureInfo.CurrentCulture.EnglishName);
```

↓これは Blazor Wasm の環境のはず。

```txt
Mono 6.5.0 (explicit/9f49cc85af1)
4.0.50524.0
Unix 1.0.0.0
System.Text.UTF8Encoding
Invariant Language (Invariant Country)
```

Blazor Wasm は CurrentCulture が常に Invariant Language だし、現状は Mono 扱いだし、OS は Unix 扱いっぽい。

**Comment by ufcpp-live** [comment]
NRT がらみはもともと「C# 9.0 での更新点」な配信回を設けようと思っていたものの、「9.0 関係なく、そろそろ1回 null 許容参照型回を設けてもいいんじゃない？」という話に。
