### ISSUE TITLE
VS 16.9 p3 出たってよ(C# Next ポロリもあるよ)

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#24]
配信URL: https://youtu.be/xS_AlnXMFwo

リリースノート等:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.9.0-pre.3.0
https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-9-preview-3/

## C# 10?

C# Next 毎年恒例、「実際あったけど QA 間に合わなくて 9.0 に入らなかったやつが今 merge された」な小さい機能あり。

![image](https://user-images.githubusercontent.com/3760955/105343101-8717e400-5c24-11eb-850c-c6ea15078440.png)

https://twitter.com/ufcpp/status/1352055289311240198

一応は「 .NET に合わせて C# も年1でメジャーリリース」っぽい空気あるのでこれを C# 10.0 Preview と呼んでいいのかどうか…
復活の LangVersion preview (2か月ぶり)。

ちなみに `{}` の中身は string のみ受け付け。 float の ToString がカルチャー依存だったりするので…

## .NET Productivity

- `#if` にインテリセンスがかかるように
- Source Generator 産の生成物が Solution Explorer に並ぶように

リリースノートの方の "Quick Info now displays compiler warning IDs or numbers for suppressions." とか言ってるのはこれ？

![image](https://user-images.githubusercontent.com/3760955/105347509-5aff6180-5c2a-11eb-9454-586ccacab330.png)

今日使う Source Generator の例、 https://github.com/microsoft/win32metadata にしようかな。

## OR_GREATER

https://twitter.com/ufcpp/status/1352092452417486849

OR_GREATER の仕様に関する話は: [OR_GREATER preprocessor symbols for TFMs](https://github.com/dotnet/designs/blob/main/accepted/2020/or-greater-defines/or-greater-defines.md)

.NET SDK 的にこの仕様が master ブランチに merge されたのは 2020/12/3 っぽい。
ワンチャン、Preview 2 の時(12/8)に有効になってた可能性ある？(未確認)

## main ブランチ

そいうや、dotnet/designs は main へのリネームしてた。
dotnet/runtime とか roslyn とかは master のまま。

**Comment by ufcpp-live** [comment]
今日の初期状態:

```cs
class Sample
{
    public int A;
    public int B;

    public const string S = $"{nameof(A)} {nameof(B)}";
}
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105492438-4d65dc80-5cfb-11eb-9636-ffd3b54f0694.png)

const string のマウスオーバー結果。
定義と展開結果両方見たくない？みたいな話に。

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Globalization;

var culture = CultureInfo.GetCultureInfo("fr-fr");
Console.WriteLine(1.2.ToString(culture));

class Sample
{
    public int A;
    public int B;

    // ダメ。数値の ToString はカルチャー依存なので const じゃない…
    public const string S = $"{1.2} {nameof(A)} {nameof(B)}";
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Globalization;

var ja = CultureInfo.GetCultureInfo("ja-jp");
var fr = CultureInfo.GetCultureInfo("fr-fr");
Console.WriteLine(int.Parse(1.2.ToString(fr), ja)); // もちろん例外！
```

**Comment by ufcpp-live** [comment]
OR_GREATER 仕様が入った日
https://github.com/dotnet/sdk/commit/c1f44b141df60245ed25a1148f3516cc971140a3#diff-7d043b70287c061ddd2cc5ccc8ad0547b629b0eb9c60f3bce15b3b0f353744b9

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105497772-a6853e80-5d02-11eb-9922-651c8879058c.png)

旧型式 csproj の場合。
TRACE と DEBUG しかねぇ…

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105499389-c289df80-5d04-11eb-8748-673b2c5f1a54.png)

これの結果、en-us に飛ぶのはいいのかどうか？

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105501075-18f81d80-5d07-11eb-9cc3-7c47f59f77d7.png)

Ctrl + , の結果
上が 16.9 p3
下が 16.8

コード生成物が出るようになりました。

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105503358-d126c580-5d09-11eb-92a0-8956aa335b76.png)

メソッドじゃねぇじゃん…
WM_CLOSE…

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/105506158-17c9ef00-5d0d-11eb-9980-344d5c20e832.png)

XamarinForms の MasterDetail が Flyout にリネームされたって。
MasterDetail で Google 検索して Flyout が出てくるのすごい。

**Comment by ufcpp-live** [comment]
かずきさん一押し 16.9 p3 機能

![image](https://user-images.githubusercontent.com/62176519/105509426-d3405280-5d10-11eb-8771-940ffeaebd79.png)

XAML からの ViewModel 生成。
INotifyPropertyChanged も生成してる。
プロパティ生成もあった。

**Comment by ufcpp-live** [comment]
今日の結論: 10年前に欲しかった。

**Comment by ufcpp-live** [comment]
ちなみに今日のBGMは https://dova-s.jp/bgm/play10983.html

**Comment by ufcpp-live** [comment]
`#if` 分岐しまくりたい類のプロジェクト設定:

```xml
<ItemGroup>
  <Compile Include="../../Common/*.cs" />
</ItemGroup>

<DefineConstants>$(DefineConstants);ServerOnly;AAAServer;BBBServer</DefineConstants>
```

**Comment by ufcpp-live** [comment]
OR_GREATER 話1

NETSTANDARDェ…

```cs
#if NETSTANDARD2_1 // OR_GREATER ない…

#if NETCOREAPP2_1_OR_GREATER
// FastSpan が使えるよ！
string.Create(2, default(object), (buffer, _) => { });
#endif
```

**Comment by ufcpp-live** [comment]
const string interpolation からの脱線。
`$"{}"` 中の `{}` の中には const string しか入れられない。
なんでかというと、数値とかの ToString はカルチャー依存…

カルチャー違うと小数点が違う…

```cs
using System;
using System.ComponentModel.Design.Serialization;
using System.Globalization;

var ja = CultureInfo.GetCultureInfo("ja-jp");
var fr = CultureInfo.GetCultureInfo("fr-fr");
//Console.WriteLine(double.Parse(1.234.ToString(ja), fr)); // 例外
Console.WriteLine(double.Parse(1.234.ToString(fr), ja)); // 1234 扱い…

Console.WriteLine(double.Parse(1.234.ToString(fr))); // CurrentCulture...

System.Threading.Thread.CurrentThread.CurrentCulture = fr;
Console.WriteLine(double.Parse(1.234.ToString(fr))); // CurrentCulture...
```

特にやばいのが、 `1.234` が 1234 扱いで Parse される…

**Comment by ufcpp-live** [comment]
OR_GREATER 話2

当初予定では NET5_0 だけで「.NET 5以降」だった。
ドタキャンかかった。
そして newer, later, greater 悩んだ結果、 OR_GREATER に。

で、.NET Framework 4.X 系と .NET 5 系は完全に別…

```cs
#if NETCOREAPP3_0
int a1;
// 当初予定、 .NET 5 でもここ通る
// 現在、 .NET Core 3.0 でのみ通る
// .NET 5 リリース直前になってダメという話に
#endif

#if NET5_0
int a2;
// 当初予定、 .NET 6 でもここ通る
// 現在、 .NET 5 でのみ通る
// .NET 5 リリース直前になってダメという話に
#endif

#if NET5_0_OR_GREATER
int a3;
// .NET SDK 5.0.200 preview でしれっと入った
// こっちの方がよく使う
#endif

#if NET451_OR_GREATER
int a4;
// .NET 5 でここ通らない！
// .NET Fx 4.8 とかでは通る
// .NET では5は4より小さかった！？
#endif
```

**Comment by ufcpp-live** [comment]
```cs
#pragma warning disable CS0168 // Variable is declared but never used ← このコメント要らなくね？ かつ、ローカライズされたの出すな！
int x;
#pragma warning restore CS0168 // Variable is declared but never used
```

**Comment by ufcpp-live** [comment]
const string interpolation やるなら nameof はセットで考えたい。
そうなったとき、引数のスコープが属性に及ばないのがちょっと残念。

```cs
[DebuggerDisplay($"{nameof(f)}")] // これはスコープ内のくせに
class C
{
    int f;

    // const $"" 的にはこの類で来てほしいけど…
    // 引数のスコープは属性まで及ばない
    [return:NotNullIfNotNull($"{nameof(x)}")] // これはダメ
    void m(int x) { }
}
```

**Comment by ufcpp-live** [comment]
const string interpolation + 引数 nameof があるとこんなことができるんだけど…

```cs
// この類の属性から
[Template($"aaa {nameof(x)} bbb")] // x がスコープ外だと無理…
public static string M(int x)
{
    // この類のコード生成したいんだけど…
    var sb = new StringBuilder();
    sb.Append("aaa ");
    sb.Append(x);
    sb.Append(" bbb");
    return sb.ToString();
}
```

**Comment by ufcpp-live** [comment]
余談: C# の const の仕様について

```cs
const int LessThanShortMax = 1;
const int GreaterThanShortMax = 1000000;

m(LessThanShortMax); // OK
m(GreaterThanShortMax); // ダメ

void m(short s)
{
}
```

**Comment by ufcpp-live** [comment]
P/Invoke 話が盛り上がった。

![image](https://user-images.githubusercontent.com/62176519/105512083-03d5bb80-5d14-11eb-9435-6bec1b5fa3a2.png)

Source Generator 製。

![image](https://user-images.githubusercontent.com/62176519/105512165-1fd95d00-5d14-11eb-8e7d-1f8ff2a4583f.png)

Source Generate 元のメタデータは  [Win32Metadata パッケージ](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata)から取ってる。

メタデータも nuget 配布なので Linux ビルドも可能。
Win32 アプリを Linux イメージで CI できる！
(さすがに実行はダメ。DllNotFound)

**Comment by ufcpp** [comment]
https://www.youtube.com/watch?t=9000&v=xS_AlnXMFwo&feature=youtu.be

Wikipedia とか読み始めたら止まらない人の時間をごりごり奪おうとする悪の軍団。
