### ISSUE TITLE
.NET 6 Preview 1 出たって

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#26]
https://youtu.be/y7kqEYov5ro

## .NET 6

アナウンス: [Announcing .NET 6 Preview 1](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-1/)

ロードマップを書いてるだけで実装ないものもありそうな予感がひしひしとしつつ。

- .NET Unification (世界情勢のせいで5から6にマイルストーン変更)がやっと
  - MAUI
  - Blazor desktop
  - XAML/Razor ホットリロード
- ARM64 対応
  - Apple Silicon も
- crossgen (AOT コンパイラー)を C# 実装しなおしたって
- profile guided optimization (動的にどのメソッドがどのくらい呼ばれてるか調べて最適化具合変える)やるって
- .NET CLI
  - rsp ファイル読むようにする
  - `dotnet [suggest]`、`dotnet [parse]`
- BCL
  - Math
    - SinCos, ReciprocalEstimate, ReciprocalSqrtEstimate
    - Clamp とかに uint オーバーロード
    - DivRem のタプル戻り値なやつ
  - Windows ACLs
  - ThreadPool がマネージ実装になったって
- Single files app、Linux 以外もサポート
- 構造体のレジスター割り当てが賢くなったって

たぶん VS 16.10 Preview も出そうな空気感あるんだけど、週末までに出なかったら CLI で。

https://twitter.com/ufcpp/status/1362205209401856001

`(var x, y) = ...;` (分解で宣言と代入の混在)できるようになってる。

## その他、C# Desing Notes

時間残れば:

- [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) に record struct と nameof(parameter) と List パターンの行増えた
- [global using は C# コードとして書けるようにする方向性](https://github.com/dotnet/csharplang/blob/3ddb3f87b9346ff8904ee43a8788aa47e82a44d1/proposals/GlobalUsingDirective.md)
- raw string
- virtual statics in interfaces

raw string の話を見てなんか久々に source generator 書いてみてたり: https://github.com/ufcpp/TextTemplateSourceGenerator

**Comment by ufcpp-live** [comment]
今日、

- lambda improvements
- using aliases allowing type parameters

みたいな提案ドキュメントも上がってた。

**Comment by ufcpp-live** [comment]
```cs
int x;
//string y;

//// 前からいける
//(x, y) = (1, "abc");

//// これも前からいける
//(var x, var y) = (1, "abc");

// new!!
(x, var y) = (1, "abc");

System.Console.WriteLine(x);
System.Console.WriteLine(y);
```

**Comment by ufcpp-live** [comment]
Math がらみとかタプル戻り値の話とか

```cs
using System;
using System.Collections.Generic;
using System.Linq;

// 最近はタプル戻り値
var (sin, cos) = Math.SinCos(Math.PI / 5);

// ↑は↓と同じ意味
//var t = Math.SinCos(Math.PI / 5);
//var sin = t.Sin;
//var cos = t.Cos;

// 昔は new ValueTuple<double, double>(sin, cos) の部分のインライン展開が効きにくかったらしい

// ちょっと前までのノリだと多分こう
//Math.SinCons(theta, out var sin, out var cons);

// 今まで
//var quotient = Math.DivRem(10, 3, out var remainder);

// これから
var (q, r) = Math.DivRem(10, 3);

// タプルの要素名は大文字始まり？
// もめた。
//new[] { 1 }.Zip(new[] { 2 });
```

**Comment by ufcpp-live** [comment]
`#if` で泣きそうになった結果、アナライザーで対処するって。

```cs
using System;
using System.Runtime.InteropServices;

// "browser" になってるけど、"browser" どうなってるのかな？
Console.Beep();

if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
{
    Console.SetWindowPosition(1, 1);
}
else
{
    // ちゃんと警告
    Console.SetWindowPosition(1, 1);
}
```

**Comment by ufcpp-live** [comment]
nint は IntPtr に属性

```cs
using System;
using System.Runtime.CompilerServices;

class C
{
    // 一応書けるけどコンパイルエラー。
    // エラー内容は「それ、コンパイラーが使ってるから手書きするな」
    // 拡張メソッドの Extension 属性とかといっしょ。
    [NativeInteger]
    IntPtr x;
}

namespace System.Runtime.CompilerServices
{
    [CompilerGenerated]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Parameter | AttributeTargets.ReturnValue | AttributeTargets.GenericParameter, AllowMultiple = false, Inherited = false)]
    internal sealed class NativeIntegerAttribute : Attribute
    {
        public readonly bool[] TransformFlags;

        public NativeIntegerAttribute()
        {
            bool[] array = new bool[1];
            array[0] = true;
            TransformFlags = array;
        }

        public NativeIntegerAttribute(bool[] P_0)
        {
            TransformFlags = P_0;
        }
    }
}
```

**Comment by ufcpp-live** [comment]
「時間残れば」系の話は時間やっぱり残らなかったので次回！

**Comment by ufcpp** [comment]
[5:21～](https://www.youtube.com/watch?t=321&v=y7kqEYov5ro)

今回、Visual Studio よりも先に .NET SDK のリリースの方が早いので…
Language Feature Status 的に「VS 16.10 に merge」となっている機能が .NET 6.0 Preview 1 に先に入ってるっぽい。

https://github.com/ufcpp-live/UfcppLiveAgenda/issues/26#issuecomment-782633759 のコードは今、コマンドラインでだけコンパイル可能。

**Comment by ufcpp** [comment]
[51:43～](https://www.youtube.com/watch?t=3103&v=y7kqEYov5ro) ReciprocalEstimate

reciprocal = multiplicative inverse (逆数 = 乗法に関する逆元)
inverse だけで(乗法の)逆数を指すこともあるけども、紛らわしい時は reciprocal を使うみたい。

除算命令はハードウェア作るの大変でものすごい遅い。
大まかな精度でいいのなら、真面目に除算命令を使うよりも、[ニュートン法](https://ja.wikipedia.org/wiki/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%88%E3%83%B3%E6%B3%95)を使って積和演算数回やる方が速かったりする。
なので Intel CPU も ARM も「1 / x の大まかな値を計算する」命令を持ってる。
その命令を呼んでくれるのが ReciprocalEstimate, ReciprocalSqrtEstimate 関数。

**Comment by ufcpp** [comment]
ACL わからん…

[1:07:42～](https://www.youtube.com/watch?t=4062&v=y7kqEYov5ro)

- とりあえず、System.Threading.AccessControl は netstandard1.3 対応
- [プラットフォーム互換性アナライザー](https://docs.microsoft.com/ja-jp/dotnet/standard/analyzers/platform-compat-analyzer)を使って警告対応してるっぽい
- 未対応プラットフォームで実行すると例外が出るはず
- `#if` 地獄、TargetFramework 地獄よりは `SupportedOSPlatform` による通常の `if` ステートメント分岐の方がマシらしい
- プラットフォーム互換性アナライザー自体は .NET 5 で入ってる
  - 一例が https://github.com/ufcpp-live/UfcppLiveAgenda/issues/26#issuecomment-782663935 の `SetWindowPosition`

**Comment by ufcpp** [comment]
[1:20:31～](https://www.youtube.com/watch?t=4831&v=y7kqEYov5ro)

- Unification
  - まあ、ロードマップ(11月の正式リリースまでにはやるという予定)ではあるものの…
- Apple Silicon 対応はもうやったはず。Apple Silicon をお持ちのお客様がいらっしゃいましたら是非人柱に…
- Calling Convention (呼び出し規約)よくわからん…

**Comment by ufcpp** [comment]
[1:33:30～](https://www.youtube.com/watch?t=5610&v=y7kqEYov5ro)

- NuGet パッケージの「来歴検証」(出どころが信用できるかどうかの検証)の話
  - [Terrapin Process](https://github.com/dotnet/roslyn/pull/49886/files)
- いろんなところに暗号通貨マインニング対策が…
  - RTX3060 がハードウェアレベルで対処してるの受ける

**Comment by ufcpp** [comment]
[1:39:34～](https://www.youtube.com/watch?t=5974&v=y7kqEYov5ro)

まあ、ロードマップなので。

**Comment by ufcpp** [comment]
[1:49:25～](https://www.youtube.com/watch?t=6565&v=y7kqEYov5ro)

- Thread Pool がマネージ実装になったって
  - CoreCLR と Mono のコード共通化のため
  - 一応前の挙動に戻すフラグはある

[1:55:49～](https://www.youtube.com/watch?t=7129&v=y7kqEYov5ro) Crossgen もポータビリティのためにマネージ実装

**Comment by ufcpp** [comment]
[2:01:26～](https://www.youtube.com/watch?t=7286&v=y7kqEYov5ro)

AOT (事前ネイティブ化)するとリフレクション時に「その型使ってない」誤判定を受けて困ること結構ある話。
Source Generator を使ってコンパイル時処理に書き換える機運あり。

**Comment by ufcpp** [comment]
[2:14:38～](https://www.youtube.com/watch?t=8078&v=y7kqEYov5ro)

CLong...
64ビットCPUでも long のサイズが32ビットなC/C++コンパイラーもあるので…
long long...

**Comment by ufcpp** [comment]
[2:17:42～](https://www.youtube.com/watch?t=8262&v=y7kqEYov5ro)

- `nint` (C# 9.0 機能)の話
- 中身は `IntPtr`
- `NativeInteger` 属性が付いてると C# からは nint に見える
- VB からはそのまま `IntPtr` 扱い
- `IntPtr` と `nint` (属性の有無)で何が変わるかというと四則演算
  - `IntPtr` は `IntPtr` の演算子オーバーロードを呼ぶはず
  - `nint` は普通にネイティブの四則演算命令を呼ぶはず
- C# 9.0 で手書きで `NativeInteger` 属性を使おうとするとコンパイル エラーになる
  - https://github.com/ufcpp-live/UfcppLiveAgenda/issues/26#issuecomment-782694199
  - これは今に始まった話じゃなくて、例えば拡張メソッドの `Extension` 属性とかも同じ

**Comment by ufcpp** [comment]
[2:30:32～](https://www.youtube.com/watch?t=9032&v=y7kqEYov5ro)

自作 Source Generator の話。
自分で言うのもなんだけど相当邪悪。

この辺りから配信が不安定になったし、本題の .NET 6 Preview 1 の話は一通りしたし、時間も2時間半超えたし、次回に持ち越すことに。
