### ISSUE TITLE
LDM 話＆ .NET Conf: Focus on Windows 周りとか

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#28]
配信枠: https://youtu.be/99ek2n6F_1U 

Visual Studio 16.9 Release と 16.10 Preview 1が来ちゃったんでそっち優先するかも。
[Ignite](https://myignite.microsoft.com/) に合わせてのリリース？

- [Visual Studio 2019 version 16.9.0](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.0)
- [Visual Studio 2019 version 16.10 Preview 1](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.1.0)

https://focus.dotnetconf.net/ とかもちょっと触れつつ。

Blazor Desktop の話ちょっとかずきさんに丸投げ気味に

- [Blazor Desktop Apps 面白そうじゃない？](https://zenn.dev/okazuki/articles/mobile-blazor-bindings)
- [Blazor 周辺を整理しながら雑談](https://www.youtube.com/watch?v=g3rU2MDG-J4&t=1017s)

あと、 https://github.com/ufcpp-live/UfcppLiveAgenda/issues/27 に書いたリスト、多分1回では終わらないので終わるところまでやる。
とりあえず3件はブログ書いたのでそれ優先

- [x] [raw string literal](https://ufcpp.net/blog/2021/2/rawstringliteral/)
- [ ] [構造体の引数なしコンストラクター](https://ufcpp.net/blog/2021/2/parameterlessstructctor/)
- [ ] [文脈キーワードの複雑さ低減](https://ufcpp.net/blog/2021/2/lexicalkeywords/)

**Comment by ufcpp-live** [comment]
```cs
using System;

int x;
var (x1, y1)
    = (x, var y) // 式の途中はダメ！
    = (1, "abc");

Console.WriteLine(x);
Console.WriteLine(y);
```

**Comment by ufcpp-live** [comment]
raw string

```cs
// C# in C# in C# in ...
// lang=csharp
const string s1 = """"""
    // lang=csharp
    var first = """""
        // lang=csharp
        var second = """"
            // まあ、多分、1段以上の highlight はしないんじゃない？
            var third = """
                abc
                """;
            """";
        """"";
    """""";

var s = @"
""abc"" // このエスケープがいや
";

var csharp = $@"
class C
{{ // このエスケープがいや
}}
";

// $""" には断固反対
```

**Comment by ufcpp-live** [comment]
```cs
// *1 と *2 が等価
var a1 = """
    abc
""";

var a2 = @"abc
";

var b1 = """
    abc""";

var b2 = @"abc";

var c1 = """
    abc



    """;

var c2 = @"abc



";

var d1 = """
  abc
    def
      ghi
""";

var a2 = @"abc
  def
    ghi
";
```

**Comment by ufcpp-live** [comment]
```cs
// 調べる
var a1 = """"
abc""""""";
// ↑を abc""" 扱いすることは可能か？
```

**Comment by ufcpp-live** [comment]
```cs
// １行目よりも小さいインデントはあり
var a1 = """
    abc
def
        ghi
""";

var a2 = @"abc
def
    ghi
";
```

**Comment by ufcpp-live** [comment]
string interpolation はアロケーションかかりすぎてやばい

なので、 https://github.com/dotnet/csharplang/pull/4486/files?short_path=77eda16#diff-77eda16068bf940c41c3c540d5a0f74c1bfee4b56388b0bc4e59e037abaa9ec7

```cs
ILogger logger;
logger.Log<(int, int, int)>(
    LogLevel.Information,
    default ,
    (1, 2, 3),
    null,
    (t, m) => $"{t.Item1} {t.Item2} {t.Item3}");

logger.LogInformation($"{1} {2} {3}"); // ログレベルによらずアロケーション
```

**Comment by ufcpp-live** [comment]
文字列処理を stack ベースにするのはむっちゃ大変。
特に await

```cs
// https://github.com/dotnet/csharplang/pull/4486
// string interpolation を ref struct + TryFormat に展開しようという話。
// ref struct だと…

// これ、OK
var s = $"{await Task.Run(() => 1)}";
// これ、どうすんだ？

async Task m()
{
    await Task.Yield();

    //Span<byte> s; // 書けない
    // 書けてもいいのに

    r(stackalloc byte[1]); // これはいける

    await Task.Yield();

    local(); // これは余裕

    await Task.Yield();

    static void local()
    {
        Span<byte> s = stackalloc byte[1];
    }
}

void r(Span<byte> s) { }

IEnumerator m1()
{
    yield return 0;

    Span<byte> s = stackalloc byte[1]; // 書ける！
    var x = s[0];

    yield return 0;
}
```

**Comment by ufcpp-live** [comment]
言語内言語？
あるよ、今のC#に、すでに。

![image](https://user-images.githubusercontent.com/62176519/109823591-6b6c1880-7c7b-11eb-9256-3f68bbf964d2.png)

**Comment by ufcpp-live** [comment]
進捗 1/3 でした
(raw string 話で終わり。途中、「improved interpolated strings spec」の話に行って、重たい話で時間食う。

**Comment by ufcpp-live** [comment]
締めの言葉

lang=csharp

**Comment by ufcpp** [comment]
[8:28～](https://youtu.be/99ek2n6F_1U?t=508) Blazor Desktop/Hybrid の話は丸投げしていい？
(https://zenn.dev/okazuki/articles/mobile-blazor-bindings の話)

**Comment by ufcpp** [comment]
[31:15～](https://youtu.be/99ek2n6F_1U?t=1875) 「困ったら安定板を使おうかと思ってやってるけど、困ることがなくて」(リリースチャネルの Visual Studio 全然使ってない話)

**Comment by ufcpp** [comment]
[45:58～](https://youtu.be/99ek2n6F_1U?t=2748) Remove Unused References

**Comment by ufcpp** [comment]
[51:56～](https://youtu.be/99ek2n6F_1U?t=3116) enum の補完が賢くなった

そもそも今、C# の文法的に `m(Blue)` のコンパイルが通るようにしたいという提案もあり。

**Comment by ufcpp** [comment]
[59:10](https://youtu.be/99ek2n6F_1U?t=3550) 改行周りのリファクタリング

**Comment by ufcpp** [comment]
[1:03:30](https://youtu.be/99ek2n6F_1U?t=3810) `(x, var y) = ...` (変数と宣言の混在分解)

**Comment by ufcpp** [comment]
[1:19:00～](https://youtu.be/99ek2n6F_1U?t=4740) Raw string

**Comment by ufcpp** [comment]
[1:22:33～](https://youtu.be/99ek2n6F_1U?t=4953) 言語内言語の話
https://github.com/ufcpp-live/UfcppLiveAgenda/issues/28#issuecomment-789769626 これとか

**Comment by ufcpp** [comment]
[1:34:19～](https://youtu.be/99ek2n6F_1U?t=5659) 複数行リテラルとエスケープしないリテラルの話

**Comment by ufcpp** [comment]
[1:49:18～](https://youtu.be/99ek2n6F_1U?t=6558) 改行とか先頭空白の話 https://github.com/ufcpp-live/UfcppLiveAgenda/issues/28#issuecomment-789749689

**Comment by ufcpp** [comment]
[1:59:11～](https://youtu.be/99ek2n6F_1U?t=7151) 行きつく先は「生 Append」
https://github.com/ufcpp-live/UfcppLiveAgenda/issues/28#issuecomment-789761195

その後ブログちゃんと書いた: [Improved Interpolated Strings](https://ufcpp.net/blog/2021/3/improvedinterpolatedstrings/)
