### ISSUE TITLE
LDM 話続き＆ .NET 6 Preview 2

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#29]
配信枠: https://youtu.be/NqJkCm85CSM

.NET 6 Preview 2 になってる。

- [Announcing .NET 6 Preview 2](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-2/)

[前回](https://github.com/ufcpp-live/UfcppLiveAgenda/issues/28)残ったやつ:

- [ ] [構造体の引数なしコンストラクター](https://ufcpp.net/blog/2021/2/parameterlessstructctor/)
- [ ] [文脈キーワードの複雑さ低減](https://ufcpp.net/blog/2021/2/lexicalkeywords/)

そこからブログ1記事増えたやつ:

- [ ] [using エイリアスの改善と global using](https://ufcpp.net/blog/2021/3/usingimprovements/)

https://github.com/ufcpp-live/UfcppLiveAgenda/issues/27 も未消化多い。

**Comment by ufcpp-live** [comment]
```cs
#nullable enable

using System.Collections.Generic;

_ = new[] { 1 }.FirstOrNull();
_ = new[] { "" }.FirstOrNull();

static class EnumerableClass
{
    public static T? FirstOrNull<T>(this IEnumerable<T> source) where T : class => null;

    // ここにあるとダメ。 .NET の型システム的に where 違いのオーバーロード無理。
    //public static T? FirstOrNull<T>(this IEnumerable<T> source) where T : struct => null;
}

static class EnumerableStruct
{
    // 別の型にあるなら OK。
    public static T? FirstOrNull<T>(this IEnumerable<T> source) where T : struct => null;
}
```

**Comment by ufcpp-live** [comment]
↑ どうせ↓みたいな分岐ができなくてつむことが多々ある。

![image](https://user-images.githubusercontent.com/62176519/111870945-f151c880-89ca-11eb-87aa-e91c403dfea9.png)

**Comment by ufcpp-live** [comment]
```cs
// 書きたいコード
//struct FixedArray4
//{
//    int[] _array = new int[4];
//    public int this[int index] => _array[index];
//}

// しょうがないから書くコード
struct FixedArray4
{
    int[] _array;

    private FixedArray4(int[] array) => _array = array;

    // これがいやーーーーー
    public static FixedArray4 Create() => new(new int[4]);
    public int this[int index] => _array[index];
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;
using System.Collections.Immutable;

// 構造体の引数なしコンストラクターがないというか、
//ImmutableArray<int> array = default;

// 今、 new() が default 扱いされてしまい…
ImmutableArray<int> array = new();

// IndexOutOfRange ほしいのに、ぬるぽが来る
// 何を new したんでしょう…
Console.WriteLine(array[0]);

// この判定が必要
Console.WriteLine(array.IsDefault);
```

**Comment by ufcpp-live** [comment]
```cs
using System;

// C# 6.0 の頃、これが構造体コンストラクターを呼んでくれないというバグあった。
var point = Activator.CreateInstance<Point>();

struct Point
{
    public int[] _data;

    // .NET のメタデータ的には昔から許されてた。
    // C# コンパイラーをちょこっといじれば可能だったらしい。
    public Point() => _data = new int[1];
}
```

**Comment by ufcpp-live** [comment]
```cs
void m(Point p = new())
{
}

struct Point
{
    // この行の有無だけで m がエラーになるかどうか変わる。
    // つまり、引数なしコンストラクターの追加は破壊的変更。
    public Point() { }
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;

void m(Point p = new()) // warning waves で警告くらいは出すべきかも
{
}

struct Point
{
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;

m2<Point>();

// 今、「struct の時点で new() を満たす」という判定を受けてる。
void m1<T>() where T : new()
{
    // new T() は中で Activator.CreateInstance<T>() を呼んでる
    Console.WriteLine(new T());
}

// 今、これ許される。
// さすがに変えれない。
void m2<T>() where T : struct => m1<T>();

struct Point
{
    // これを足すと破壊。
    // new T() のところでアクセス許されない例外が出る。
    private Point() { }
}
```

**Comment by ufcpp-live** [comment]
```cs
using System;

unsafe
{
    Console.WriteLine(sizeof(Empty)); // これ1
}

struct Empty { }
```

**Comment by ufcpp-live** [comment]
```cs
var var = new var();
class var { }

@record record = new record();
record record { }
```

**Comment by ufcpp-live** [comment]
Roslyn みたいにsemantics見まくってるもの同水準は期待できない。

![image](https://user-images.githubusercontent.com/62176519/111873048-cae35b80-89d1-11eb-80b6-932f75b748da.png)

**Comment by ufcpp-live** [comment]
```cs
// これ、破壊的変更するかも。
// 今後、semantics 見なくても「var はここで出てきたらキーワード」扱いしたい
var var = new var();

// record はそうだから。
// そして C# 9.0 がリリースされて、それで困った人もいない。
record record = new record();

// @ を付ければいいじゃない。
//@record record = new record();

class var { }
record record { }
```

**Comment by ufcpp-live** [comment]
![Uploading image.png…]()

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/111873935-2283c600-89d6-11eb-8c03-4349d42e7d43.png)

**Comment by ufcpp-live** [comment]
```cs
global using System;
using System;

// これ OK
using D = System.DateTime;

// これダメ
// global using でもダメということにするらしい。
// global using はべたに「すべてのファイルの先頭にその using を展開」扱い。
using D1 = DateTime;
;

namespace A
{
    // これは OK
    using D = DateTime;
}
```

**Comment by ufcpp-live** [comment]
sharplab 仕事はえぇ

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQHEA2B7YVMCqyAlgHYDmAIsUgMYzEBuEAPgMSlyaZTCYQACCKV78AsAChJAemkCoCqJMnkceTAIACAJgCMyiTv0SgA==

**Comment by ufcpp-live** [comment]
```cs
using System;

var x = 1;

// エイプリルフールその1、オタマジャクシ演算子
Console.WriteLine(~-x);
Console.WriteLine(-~x);
```

**Comment by ufcpp-live** [comment]
「 60進数リテラル」「エイプリルフール」

**Comment by ufcpp** [comment]
[2:34～](https://youtu.be/NqJkCm85CSM?t=154) 開幕「きのこ」「たけのこ」「どうでもいい」「そっとしておこう…」

**Comment by ufcpp** [comment]
[8:36～](https://youtu.be/NqJkCm85CSM?t=516) .NET 6 Preview 2 「開発ループの改善をしたい」

**Comment by ufcpp** [comment]
[28:30～](https://youtu.be/NqJkCm85CSM?t=1710) PriorityQueue

**Comment by ufcpp** [comment]
[41:55～](https://youtu.be/NqJkCm85CSM?t=2515) SignalR に nullable アノテーション付いたらしい → 制約なし `T?` とか `MemberNotNull` がないとやっぱきついよねみたいな話

**Comment by ufcpp** [comment]
[45:34～](https://youtu.be/NqJkCm85CSM?t=2734) `FirstOrNull` からの、`where` 違い拡張メソッドオーバーロード

**Comment by ufcpp** [comment]
[54:22～](https://youtu.be/NqJkCm85CSM?t=3262) NullableContext 属性の話

**Comment by ufcpp** [comment]
[59:40～](https://youtu.be/NqJkCm85CSM?t=3580) 構造体の引数なしコンストラクター

**Comment by ufcpp** [comment]
[1:22:30～](https://youtu.be/NqJkCm85CSM?t=4950) `C##`

平均律だと D = C## だけど、純正率だと厳密には違う音なんだっけ？

**Comment by ufcpp** [comment]
[1:27:20～](https://youtu.be/NqJkCm85CSM?t=5240) C# 1.0 でジェネリクスなかったから3年くらいは悲しかった

**Comment by ufcpp** [comment]
[1:46:43～](https://youtu.be/NqJkCm85CSM?t=6403) class は(文脈抜きで)単純にキーワードなので C# だと `@` 必須
からの、「他の言語で `klass` とか `clazz` とかよく見た」話。

[1:48:10](https://youtu.be/NqJkCm85CSM?t=6490) 「cls とか略すと clear screen? ってなる」「C# script には `#cls` ディレクティブで実際 clear screen する文法がある」

**Comment by ufcpp** [comment]
[1:55:52～](https://youtu.be/NqJkCm85CSM?t=6952) ZWJ (U+200D)を使って複数の文字を1つの絵文字に結合するえぐい仕様の話

**Comment by ufcpp** [comment]
[2:24:57](https://youtu.be/NqJkCm85CSM?t=8697) 「global using 使いたいと思わない」とかいうけど、ソースコード新規追加したときのデフォルトの `using` うざいじゃない
特に `System.Text`。単独で使いたいのは `StringBuilder` しかいない。
(`Encoding` とかはだいたい `System.IO` とセット。)
(`Regex` は `System.Text.RegularExpressions` 名前空間。)
実際、「`StringBuilder` は `System` 名前空間にあるべきだった」って言われてる(中の人が反省してるの見たことある)。

**Comment by ufcpp** [comment]
[2:31:33～](https://youtu.be/NqJkCm85CSM?t=9093) Unicode の仕様がらみの話に

**Comment by ufcpp** [comment]
[2:45:42](https://youtu.be/NqJkCm85CSM?t=9942) この週末は YouTube の調子ほんと悪かった
「YouTube 君さ～」

**Comment by ufcpp** [comment]
[2:48:40～](https://youtu.be/NqJkCm85CSM?t=10120) エイプリルフールネタはやらないというか、「真に受けられて困る嘘はつくな」話
