### ISSUE TITLE
.NET 6 Preview 3 とか

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#31]
配信URL: https://youtu.be/coUeSb4Q_Q8

出たって。

- [Announcing .NET 6 Preview 3](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-3/)
- [ASP.NET Core updates in .NET 6 Preview 3](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-preview-3/)

話題:

- Ben Adams さん祭りなのでは…
- CollectionsMarshal.GetValueRef 
- ASP.NET & Blazor の hot reload 気になる
- .NET ランタイムのコードも成るべく C++ から C# に移植することでコミュニティ貢献がはかどる
- [`BlazorWebView` は okazuki さんが早速試してみてた](https://twitter.com/okazuki/status/1380447925478719489)

他、元々やろうかと思ってたネタ(時間があれば or 次回):

- [C# 8.0 で DIM](https://ufcpp.net/study/csharp/cheatsheet/ap_ver8/#default-imeplementation-of-interface)
- [C# 9.0] で covariant returns](https://ufcpp.net/study/csharp/cheatsheet/ap_ver9/#class-covariant-returns)
- この流れで、[C# 10.0 でまた型システムに手を入れそう](https://ufcpp.net/blog/2021/4/staticvirtual/) (これまでよりも大き目)

**Comment by ufcpp-live** [comment]
.NET 6 B3n. Ben.

```cs
IA1 a1 = new A(); // 速い
IA6 a2 = new A(); // 遅い

public interface IA1 { }
public interface IA2 { }
public interface IA3 { }
public interface IA4 { }
public interface IA5 { }
public interface IA6 { }

public class A : IA1, IA2, IA3, IA4, IA5, IA6
{
}
```

これのインターフェイス探索の速度改善も Ben。

**Comment by ufcpp-live** [comment]
スピード狂専用メソッド追加。 by Ben.

```cs
var d = new Dictionary<int, int>(4);

for (int i = 0; i < 4; i++)
{
    d.Add(i, i);
}

ref var r = ref CollectionsMarshal.GetValueRefOrNullRef(d, 0);
d.Remove(0);
d[4] = 10;

r = 2; // capacity = 4 で作ったので、d[0] と d[4] が同じ bucket に入る

Console.WriteLine(d[4]); // 2 になってる
```

**Comment by ufcpp-live** [comment]
IsNullRef **実用化**

```cs
var d = new Dictionary<string, int>();

d["abc"] = 1;

ref var r = ref CollectionsMarshal.GetValueRefOrNullRef(d, "abc1");

if (!Unsafe.IsNullRef(ref r))
{
    r = 2;
}

Console.WriteLine(d["abc"]);
```

**Comment by ufcpp** [comment]
[3:02](https://youtu.be/coUeSb4Q_Q8?t=182) 話が逸れないうちにホットリロードの話してしまおう

**Comment by ufcpp** [comment]
[5:10](https://youtu.be/coUeSb4Q_Q8?t=310) てめぇはダメだ (.NET 6 からは Kestrel の方がデフォルトになるはず)

**Comment by ufcpp** [comment]
[12:21](https://youtu.be/coUeSb4Q_Q8?t=741) XAML は脳内レンダリング

**Comment by ufcpp** [comment]
Wasm、Native AOT がないと厳しいよなぁ話

[58:50](https://youtu.be/coUeSb4Q_Q8?t=3530) (ビルド結果のサイズ確認のためとりあえず) publish してみる

**Comment by ufcpp** [comment]
[4:24](https://youtu.be/coUeSb4Q_Q8?t=264), [1:17:48](https://youtu.be/coUeSb4Q_Q8?t=4668) WPF (BlazorWebView)はかずきさんに丸投げ

**Comment by ufcpp** [comment]
今回、本題逸れた話題少な目。

[2:07:48](https://youtu.be/coUeSb4Q_Q8?t=7668) 「画像処理のマネージ実装ないのかな」→「どう考えてもしんどそう」
