### ISSUE TITLE
Visual Studio 16.10 Preview 2 出たのと、その先の話(2022)

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#32]
配信URL: https://youtu.be/-C33H3XH-iA

[Visual Studio 2019 v16.10 Preview 2 Releases Today](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-preview-2/) (4月14日)

C# の更新はないんだけど、いくつかの IDE 機能が面白そうだったので1配信取ってもいいかも。

- Completions for Casts, Indexers, and Operators
- Automatically Insert Method Call Arguments
- User Interface for EditorConfig Files
- Visualize Inheritance Chains

[Visual Studio 2022](https://devblogs.microsoft.com/visualstudio/visual-studio-2022/)

- 64ビット(10年来の悲願)
- 他、アイコン変わるとかフォント変えるとか(あっ…ほら…ね…うん… (反応薄め))

**Comment by ufcpp** [comment]
```cs
public class A
{
    public virtual void M() { }
}

namespace NS1
{
    public class B : A
    {
        public override void M()
        {
            base.M();
        }
    }
}

namespace NS2
{
    public class B : A
    {
        public override void M()
        {
            base.M();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/3760955/114996850-37bb1a00-9eda-11eb-9040-4c8badec2689.png)

**Comment by ufcpp** [comment]
```cs
From a = new();
var b = ((To)a);

public struct From
{
    public int Value;

    public static explicit operator To(From x) => new() { Value = x.Value };

    public int this[int i] => i * Value;
}

public struct To
{
    public int Value;
}
```

![image](https://user-images.githubusercontent.com/3760955/114997519-e2cbd380-9eda-11eb-9ffa-90ac80e12b1b.png)

**Comment by ufcpp-live** [comment]
```cs
_ = new A().b.Name;
_ = (B)new A().Name; // こう生成されるとまずい
_ = ((B)new A()).Name; // こう生成される

_ = new A().b;
_ = ((B)new A()); // むしろ 不要な () 消すか？ リファクタリング対象
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/115562752-c58b7080-a2f1-11eb-9dea-32a02b4797db.png)

↑えっ、これがいけるんなら配列の .this も…

**Comment by ufcpp-live** [comment]
```cs
new A().c // ダメだって。 explicit なときだけ

class A
{
    public static explicit operator B(A _) => null;
    public static implicit operator C(A _) => null;
    public int B;

    public int Name;
}
class B
{
    public int Name;
}
class C
{
}
```

**Comment by ufcpp-live** [comment]
```cs
new A().b // こっちは出ない。 cast が自分の側にある時だけ

class A
{
}
class B
{
    public static explicit operator B(A _) => null;
}
```

**Comment by ufcpp-live** [comment]
```cs
//var (x, y, z) = (2, 3, 5);
A.X(0, 0, 0)
```

変数ないとデフォルト値が入った。

**Comment by ufcpp-live** [comment]
```cs
A.X(0, 0, 0)

public class A
{
    public static int X(int x, int y, int z = 2) => x * y * z;
}
```

**Comment by ufcpp-live** [comment]
```cs
A.X(0, 0, null) // 警告ｗｗｗｗｗ

public class A
{
    public static int X(int x, int y, params int[] z) => x * y * z.Length;
}
```

**Comment by ufcpp-live** [comment]
![Uploading image.png…]()

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/115569945-a7753e80-a2f8-11eb-91bb-66e31f2da780.png)

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/115570124-d25f9280-a2f8-11eb-8efc-dbd357e565f5.png)

**Comment by ufcpp** [comment]
https://youtu.be/-C33H3XH-iA?t=119 いつもよりも短めで終わることを期待して配信しております(結局3時間)

この時点でコメントで (3時間) って書いてる人いてマジで3時間。

**Comment by ufcpp** [comment]
[44:30](https://youtu.be/-C33H3XH-iA?t=2670) フォントとかアイコンとか視認性向上
[48:44](https://youtu.be/-C33H3XH-iA?t=2924) ダークモード

話ちょっとそれて:
[51:41](https://youtu.be/-C33H3XH-iA?t=3101) 背景画像話

[55:36](https://youtu.be/-C33H3XH-iA?t=3336) プログラミング合字とかほんと誰得
[1:02:10](https://youtu.be/-C33H3XH-iA?t=3730) いつまで「SJIS にある文字以外は環境依存文字扱い」にするのか…
[1:03:20](https://youtu.be/-C33H3XH-iA?t=3800) 顔郵便マーク(ポストンくん)
[1:04:40](https://youtu.be/-C33H3XH-iA?t=3880) JISマーク(しかも旧ロゴ)
[1:05:36](https://youtu.be/-C33H3XH-iA?t=3936) ベンゼン環は ⌬ と ⏣ の2文字ある。[化学老人会](https://twitter.com/ufcpp/status/1384888810815639553)
[1:08:54](https://youtu.be/-C33H3XH-iA?t=4134) 商標系の文字は今後もう Unicode 化されない。というか Apple ロゴ…

[1:14:22](https://youtu.be/-C33H3XH-iA?t=4462) 他って何か 2022 の話題ありそう？ → LiveShare にチャット追加、VS for Mac のリフレッシュ
