### ISSUE TITLE
_x

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#34]
配信URL: https://www.youtube.com/watch?v=uZa_FRXBTS0

元々は「[Visual Studio 16.10 Preview 3 出てるよ](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.3.0)」辺りをネタにしようかと思ってたんだけど。

一応、C# にも [sealed record ToString](https://github.com/dotnet/csharplang/issues/4174) ってのが merge されてる。

サンプルコード: https://gist.github.com/ufcpp/54a1346667e4c418706fa3bbe4ff025e

地味と言うかなんというかバグ修正と言われても信じそうなレベル。
(一応意図的に禁止してたけど、言われてみたら認めてもいいかもしれないくらいのノリ。)

そんな中、「今更 private/internal フィールドには `_` プレフィックスを付ける規約が[公式ドキュメント](https://docs.microsoft.com/ja-jp/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)に入った」とかいう話題が出てて、これを拾うかどうか… みたいなお気持ちで先週末を過ごしてた。

結局どうすることにしたかは issue タイトルを見てもらえばお察し。

Twitter アンケート:
https://twitter.com/chomado/status/1393061118428409857

きのこ・たけのこよりも僅差じゃねぇか。
https://twitter.com/ufcpp/status/1373107659994406912

**Comment by ufcpp** [comment]
ネタ的な話:

- 今日の配信は `_x` 派2人 VS `this.x` 派1人なので数の暴力でパワハラ裁判になります

マジレスな話:

- ツールで静的解析でもするのでなければとやかく言ってもしょうがないと思う
- が、最近この手の規約チェック的な analyzer が標準(SDK 同梱)で有効化される流れになってる
  - `_` 規約もそっちを覚悟しといた方がいいかも
  - .editorconfig で切り替えできる前提にはなると思うものの…
  - なので、.editorconfig に怪しい挙動がないかの方を警戒しとかないとまずそうな気がする

参考:
https://twitter.com/ufcpp/status/1393093787941892105
https://twitter.com/ufcpp/status/1392021782194839553
https://twitter.com/ufcpp/status/1394502050277326850
https://twitter.com/ufcpp/status/1394503500202057728

**Comment by ufcpp-live** [comment]
せっかくなので `_abc` と `_あいう`  の扱いの差の話もする？

**Comment by ufcpp-live** [comment]
配信初期状態:

```cs
using System;
using static System.Console;
using System.Globalization;
using System.Threading;

//Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-fr");

var x = double.Parse("1.234");

WriteLine(x);
```

**Comment by ufcpp-live** [comment]
```cs
var c = '﷽'; // UTF-16 １文字です。
Console.WriteLine(char.GetUnicodeCategory(c)); // さすがに Symbol です。
```

**Comment by ufcpp-live** [comment]
```cs
// 東アジア      yy/MM/dd
// 大陸ヨーロッパ dd/MM/yy
// 米            MM/dd/yy (InvariantCulture)
var x = DateTime.Parse("10/05/01", CultureInfo.InvariantCulture);

// 米でも yyyy/MM/dd
var y = DateTime.Parse("2010/05/01", CultureInfo.InvariantCulture);
```

**Comment by ufcpp-live** [comment]
```cs
using This = C;

// これと同レベルだろやめろ…
//#define { begin
//#define } end

class C
{
}
```

**Comment by ufcpp-live** [comment]
C++ 時代に `this->m_x` とか書いてたやつがいるらしい。

**Comment by ufcpp-live** [comment]
「つけれるものは全部つけとけ」

```cs
global::System.Int32 x = 1;
```

**Comment by ufcpp-live** [comment]
```cs
DateTimeOffset d = default(DateTime); // これだけで範囲外例外(offset が + の国限定)
```

**Comment by ufcpp-live** [comment]
```vb
Module Program
    Sub Main(args As String())
        Dim x = ３ ＊ ３ 
        Console.WriteLine(x)
    End Sub
End Module
```

おわかりいただけるだろうか。

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/118671961-db2d8080-b832-11eb-8144-b7518f313209.png)
