### ISSUE TITLE
Visual Studio 2022 Preview 1

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#37]
配信URL: https://youtu.be/lepmu9UTCgo

前回(https://github.com/ufcpp-live/UfcppLiveAgenda/issues/36 )、先に record struct, global using ネタで配信することに決めた後に Visual Studio 2022 が出て来たので「それは後回し」って言ってた分。

* [Visual Studio 2022 Preview 1 now available!](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-preview-1-now-available/)
  * 1週間くらい使ってみて今のところほんと「64ビット化した」以外の差を感じてない
    * メモリ富豪的に使えてるなぁとか
    * やっぱ結構な数の拡張が対応してないなぁとか
* [Announcing .NET 6 Preview 5](https://devblogs.microsoft.com/dotnet/announcing-net-6-preview-5/)
  * Use String.Contains(char) instead of String.Contains(String) 気になってる
    * `@""` で改行1文字だけ入れた時、git の auto-crlf にやられる
  * UnsupportedOSPlatformGuard (昔配信で触れたことあるけど当時はアナライザーがちゃんとしてなかった)
  * JsonSerializer Source generation
    * 最終的には SDK 組み込みの source generator になるって言われてるんだけど
    * 今のところたぶん SDK 組み込みでは動いてなさそうな気配感じる
  * あと、相変わらずパフォーマンス改善系が山ほどあるけど

あと、Roslyn の [Language Feature Status](https://github.com/dotnet/roslyn/blob/main/docs/Language%20Feature%20Status.md) が更新されてて、

* C# 10.0 の項目が入った
  * 現状 main に merge 済みなやつは 10.0 で確定
  * たぶん、次のリリースから LangVersion 10 が使える
  * 前回まで(VS 2022 preview 1 まで)で入ってるやつに加えて、 preview 2 で Async method builder override が出そう
* 残りの「C# Next」に入りっぱなしなやつも結構作業終わりそうな感じのやつはある
* 逆に C# 10.0 リリーズ時点で LangVersion preview 必須なまま残すみたいな話が出てるやつもちらほら見る
  * Static Abstract Members In Interfaces と List patterns 辺り

**Comment by ufcpp-live** [comment]
メモ: 次のプレビューが来たら PeriodicTimer 試す。

**Comment by ufcpp-live** [comment]
```cs
global using Timer = System.Threading.PeriodicTimer;
```

**Comment by ufcpp-live** [comment]
```cs
// これやってしばらく運用してみてどこかで困るかやってみるのはありか
global using Date = System.DateOnly;
global using Time = System.TimeOnly;
```

**Comment by ufcpp-live** [comment]
```cs
        get => @field; // AT フィールド
```

**Comment by ufcpp-live** [comment]
```cs
// これ、前向きなはずだけど、Feature Status にはまだ並んでない
class X
{
    public string Value
    {
        get => field;

        [MaybeNull]
        set => field = value ?? ""; // PropertyChanged とかで大活躍予定
    }
}
```

**Comment by ufcpp-live** [comment]
```cs
class X
{
    private string field;

    public string Value
    {
        get => field; // これどうする？破壊する？1回 Warning Wave はさむ？

        [MaybeNull]
        set => field = value ?? "";
    }
}
```

**Comment by ufcpp-live** [comment]
AT フィールド™
