### ISSUE TITLE
Visual Studio 2022 も RC

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#47]
配信URL: https://youtu.be/rumE3mORrdk
2021/10/17日 13:00～ 予定。

ブログでの公式発表系:

* [RC ですって](https://devblogs.microsoft.com/visualstudio/join-us-november-8th-for-the-launch-of-visual-studio-2022/)
  * go-live
  * 2022 (17.0) の配信にも「リリースチャネル」が出来ました
    * RC → そのままアップデートを待ってれば GA (generally available: 正式リリース)が来る
      * ちなみに、「[2019消すか](https://twitter.com/ufcpp/status/1448294828404404231)」とか言ってたのはまだやってない
    * Preview 5 → そのままアップデートを待ってれば 17.1 Preview 1 になる
  * 11月8日 8:30 PST (日本時間 9日 0:30) にバーチャル ローンチ イベント
* [.NET 6 RC 2](https://devblogs.microsoft.com/dotnet/announcing-net-6-release-candidate-2/)
  * まあ、バグ修正くらいしかないはず
  * C# 10 の話は「やっとまとまった文章が出た」であって、この配信聞いてる人にとって新ネタはないはず
  * macOS と Windows の ARM64 が安定したらしい？
* [ASP.NET in .NET 6 RC 2](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-6-rc-2/)
* [MAUI Preview 9](https://devblogs.microsoft.com/dotnet/announcing-net-maui-preview-9/)

ちなみに、C# 10 の修正点(バグ修正というか、「やっぱまずかった？」的な修正):

```cs
public void M()
{
    // 前まで: ambiguous エラー
    // RC 2で: Action の方に行く
    Method(() => { });
}

void Method(Action action) { }
void Method(Expression expr) { }
```

色…

* https://twitter.com/ufcpp/status/1448495864297578498

この時期、もう新機能の PR は次(VS 17.1 とか .NET 7 Preview)向けにでてるわけですが:

* [lambda 戻り値の `var` は禁止だって](https://github.com/dotnet/roslyn/pull/57152/files)
* [C# 11 に入りそうなやつのうち、すぐに取り掛かってそうなやついくつか](https://twitter.com/ufcpp/status/1446648374699036678)
  * semi-auto properties
  * required properties
  * top level statement attribute specifierprimary constructors
  * params Span
* low level hackathon とかいうイベント(中の人で？)やってたらしい
  * (GitHub 上では結果だけしか見えてこないのでよくわかんないけど)
  * roslyn/pull/57135 `ref` type arguments in delegates
  * runtime/pull/60428 `Unsafe.StackAllock<T>`
  * runtime/pull/60451`RuntimeHelpers.CreateSpan<T>`
  * runtime/pull/60327 `byte` 以外に対しても `ReadOnlySpan` 最適化掛けたい？

[LDM 2021/10/13](https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-10-13.md):

* `DoesNotReturn` はやっぱこれまで通りあくまで NRT 用
  * never/bottom type が求められる
* [lowercase type names](https://twitter.com/ufcpp/status/1448938279022174216)
* [Length pattern](https://twitter.com/ufcpp/status/1448527892921532424)

**Comment by ufcpp** [comment]
そうそう、前回の配信の最後の方の雑談で触れてた C# ソースコードのシンタックスハイライトした状態のものを HTML としてコピーする GUI アプリ、リポジトリ独立させた:

https://github.com/ufcpp/RoslynCsharpToHtml/issues

**Comment by ufcpp** [comment]
前半は「[WeekRef.NET](https://weekref.net/2021/10/15/updates)を見て」であっさり済ますかも？
(まゆきさんに感謝。)

**Comment by ufcpp-live** [comment]
```cs
[main:STAThread]

{ }
```

**Comment by ufcpp-live** [comment]
```cs
using System.Text;
namespace ConsoleApp1;
using System.Text.RegularExpressions;

internal class Class1
{
    private StringBuilder s;
    private Regex r;
}
```

**Comment by ufcpp-live** [comment]
```cs
namespace ConsoleApp1;
namespace A; // ダメ！
```

**Comment by ufcpp-live** [comment]
案外知らない人がいたらしい nested namespace

```cs
namespace ConsoleApp1.A
{
    record R();
}

namespace ConsoleApp1
{
    namespace A
    {
        record R();
    }
}
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/137611993-a51fa82b-ef3b-4b8d-8b7d-a61ff3580980.png)

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/137612127-ac0c417e-fbcf-483c-9faa-a100388b4abc.png)

**Comment by ufcpp-live** [comment]
```cs
class C
{
    public int X { get => field; set; } // これの話が semi-auto property
}
```

**Comment by ufcpp-live** [comment]
```cs
class C
{
    // 片方だけの semi-auto も可能
    public int X { get => field; set; }
    public int Y { get; set => field = value; }
}
```

**Comment by ufcpp-live** [comment]
```cs
class C
{
    public int X { get; set => r = ref field; }
    private ref int r; // (別提案) ref field が入った暁にはもしや…
}
```

**Comment by ufcpp-live** [comment]
value の扱い、キーワードじゃないんだ…

```cs
var c = new C();
c.X = 1;
Console.WriteLine(c.A);
Console.WriteLine(nameof(int));//行けない
Console.WriteLine(nameof(System.Int32));//いける

class C
{
    public string A;
    public int X { get => 0; set => A = nameof(value); }//行けるの？！！
    public void M()
    {
        A = nameof(this); //だめ！
    }
}
```

**Comment by ufcpp-live** [comment]
```cs
var x = 1; // これを常に型推論の var 扱いしたいという話もあり。

record var();
```

**Comment by ufcpp-live** [comment]
```cs
record var(); // 全部小文字の型名は警告にレベルが上がるかも
record @var(); // 警告消したきゃ @ 付けとけ
class @class { }
```

**Comment by ufcpp-live** [comment]
```cs
// lowlevelhackathon とかいう不穏な名前のブランチでの出来事なので、
// まだ main に merge されるとは限らない話。
using System.Runtime.CompilerServices;

m("a", "b", "c");

//↓こうなる予定
Span<string> s = RuntimeHelpers.StackAlloc<string>(3); // intrinsic method
s[0] = "a";
s[1] = "b";
s[2] = "c";
m(s);

void m(params Span<string> spans) // ROS も OK。(Memory は自信ない。)
{
}

// ずっと、StackAlloc のところだけがネック
// 懸念: GC 負担大丈夫？
```

**Comment by ufcpp-live** [comment]
```cs
// これはこれでほしい
// params Span とは別提案
// やるとしたら多分 immutable collection initializer が先
void m(params ImmutableArray<string> spans)
{
}
```

**Comment by ufcpp-live** [comment]
```cs
int getOffsetX0(Direction dir)
{
    switch (dir)
    {
        case Direction.Up: return 0;
        case Direction.Down: return 0;
        case Direction.Left: return -1;
        case Direction.Right: return 1;
        default: return 0;
    }
}

int getOffsetXダメな例(Direction dir)
{
    var table = new[] { 0, 0, -1, 1 }; // ここでアロケーションがやばいｗｗ
    return table[(int)dir];
}

int getOffsetXこれなら大丈夫な例(Direction dir)
{
    ReadOnlySpan<sbyte> table = new sbyte[] { 0, 0, -1, 1 }; // こうすると早くなる。アロケーション消える
    return table[(int)dir];
}

enum Direction
{
    Up,
    Down,
    Left,
    Right,
    // もしくは東西南北
}
```

**Comment by ufcpp-live** [comment]
```cs
var f = static () => C.State++;

Console.WriteLine(f());
Console.WriteLine(f());
Console.WriteLine(f());

class C
{
    public static int State; // mutable static が地雷(元から)
}
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/137614153-46f735c6-4faa-4ba0-a97c-c700fcf223e1.png)
