### ISSUE TITLE
C# 10.0 / .NET 6.0 / Visual Studio 2022 正式リリース記念

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#49]
配信URL: https://youtu.be/-5jmoMUCQnc

[前回最後に話した通り](https://github.com/ufcpp-live/UfcppLiveAgenda/issues/48#issuecomment-955714247)、

* タイトル: C# 10.0 正式リリース記念
* 内容: C# 10 の機能一覧を乗せといて「何か質問ある？」「雑談しようよ」

PST 8日8時半 (日本時間9日)にリリースされてるはずなので、9日の夜に配信しようかと。
[Visual Studio 2022 のローンチ イベント](https://visualstudio.microsoft.com/ja/launch/) は終わってて、[.NET Conf](https://www.dotnetconf.net/) は開催直前なタイミング。

雑談の肴に、C# 10.0 機能一覧: https://github.com/ufcpp/UfcppSample/issues/342

* Record structs
* Global Using Directive
* Improved Definite Assignment
* Constant Interpolated Strings
* Extended property patterns
* Mix declarations and variables in deconstruction
* Async method builder override
* Lambda improvements
* Interpolated string improvements
* File-scoped namespace
* Parameterless struct constructors
* Caller expression attribute
* Sealed record ToString
* Source Generator V2 APIs
* Enhanced #line directive
* Static Abstract Members In Interfaces C# 10 Preview
* Generic attributes

**Comment by ufcpp** [comment]
「やっちまいな」リスト:

* [CI の dotnet-version 上げる](https://github.com/ufcpp/StringLiteralGenerator/commit/ecb32122743004806a3feb3af075cb4196e4a570#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R14)
* [editorconfig で file-scoped namespace を優先する設定入れる](https://github.com/ufcpp/RoslynCsharpToHtml/blob/main/.editorconfig#L5)
* [ImplicitUsings true](https://github.com/ufcpp/RoslynCsharpToHtml/blob/main/Directory.Build.props#L5)

**Comment by ufcpp** [comment]
一応、今日出たっぽいブログ

https://devblogs.microsoft.com/dotnet/announcing-net-6/
https://devblogs.microsoft.com/dotnet/welcome-to-csharp-10/

**Comment by ufcpp** [comment]
いくつかのプロジェクトを Convert to file-scoped namespace を solution 全体に対して機械的にかけた結果、

* スペース込み 1.3万、2.1万行
* 「Hide white space」時差分は大体400行くらい

だった。

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/140923698-85d8fe01-77d7-49e4-986f-4d9385fdfbb5.png)

**Comment by ufcpp-live** [comment]
17.1 以降限定

![image](https://user-images.githubusercontent.com/62176519/140923778-c365979b-874f-4f70-85f1-dff4818cb8f9.png)

**Comment by ufcpp-live** [comment]
いつまでベータ？

![image](https://user-images.githubusercontent.com/62176519/140927257-de73747b-68cc-4659-bf08-e09c0437e08b.png)

**Comment by ufcpp-live** [comment]
みんなー、global using で自前 LINQ の地雷は踏んだー？？

```cs
namespace X;

// EnumerableEx にも MaxBy がいたとして、
// 拡張メソッドの解決、内側優先なので、内側に using を書けば OK。
using static ConsoleApp1.EnumerableEx;

class Program
{
    public void M()
    {
        var x = new[] { 1, 2, 3, 4, 5 }.MaxBy(x => x);
    }
}
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/140931048-f2b7208e-8614-4109-96be-50556094bd92.png)

**Comment by ufcpp-live** [comment]
アンケート事案:

これ、生理的に受け付ける？

```cs
namespace ConsoleApp1;

public class Class1
{
}
```

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/140938197-1e1c97af-a46e-47d2-9e97-5e9777b5c1f3.png)

**Comment by ufcpp-live** [comment]
うちで「net6.0 にしただけで単体テストがこけた」の１つ:

```cs
var m = new MemoryStream();
var w = new StreamWriter(m);
w.Write("aqswdefrgtyhujik");

var data = m.ToArray();

// 実際にはここに CryptoStream 挟んでる
var r = new MemoryStream(data);

var buffer = new byte[data.Length];
r.Read(buffer);

// buffer の後ろの方が0のまま残ってた。
Assert.Equal(data, buffer);

// 修正結果

int totalRead = 0;
while (true)
{
    var read = r.Read(buffer.AsSpan(totalRead));
    if (read == 0) break;
    totalRead += read;
}
```

**Comment by ufcpp-live** [comment]
左、いいよ！

![image](https://user-images.githubusercontent.com/62176519/140941834-e5635b9a-78e0-4dcf-9f21-b20d652230d1.png)
