### ISSUE TITLE
【C# 9.0/.NET 5候補】Source Generator を試してみる回

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#5]
https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/

.NET 5 Preview 3で入ってたらしいもの、C# チームの人がブログで説明してた。

- ブログの説明通りに試しにやってみる
- [公式サンプル](https://github.com/dotnet/roslyn-sdk/tree/master/samples/CSharp/SourceGenerators) を試してみる
- デバッグとかどうしよう
- "first preview" らしいところ
  - 生成が掛かるタイミング、dll 再読み込み、F12 ナビゲーション、F11 ステップインとかの話
    - [実行タイミング](https://github.com/dotnet/roslyn/blob/4ce9f2d507f7a774a9563ac584c1bf911dea66c5/src/Compilers/Core/Portable/CommandLine/CommonCompiler.cs#L789)
    - [LangVersion.Preview](https://github.com/dotnet/roslyn/blob/bc2d6a2597d07a574be4e292f9dbd9c8f975fd7f/src/Compilers/CSharp/Portable/CommandLine/CSharpCompiler.cs#L405)
    - Receiver
  - C# の文法的な話(現状何も実装ない/提案)
    - [Extending Partial Methods](https://github.com/dotnet/csharplang/blob/master/proposals/extending-partial-methods.md)

https://stackoverflow.com/questions/55244265/use-roslyn-code-analyzer-in-same-solution

**Comment by ufcpp** [comment]
```cs
using Generator1;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using System;
using System.Collections.Immutable;
using System.IO;

class Program
{
    static void Main()
    {
        var source = @"class Program { static void Main() { } }";

        var compilation = Compile(source);

        foreach (var diag in compilation.GetDiagnostics())
        {
            Console.WriteLine(diag);
        }
    }

    private static Compilation Compile(string source)
    {
        var dotnetCoreDirectory = System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory();
        var compilation = CSharpCompilation.Create("test",
            syntaxTrees: new[] { SyntaxFactory.ParseSyntaxTree(source) },
            references: new[]
            {
                    AssemblyMetadata.CreateFromFile(typeof(object).Assembly.Location).GetReference(),
                    MetadataReference.CreateFromFile(Path.Combine(dotnetCoreDirectory, "netstandard.dll")),
                    MetadataReference.CreateFromFile(Path.Combine(dotnetCoreDirectory, "System.Runtime.dll")),
            });

        // ここから
        var opt = new CSharpParseOptions(kind: SourceCodeKind.Regular, documentationMode: DocumentationMode.Parse);
        var driver = new CSharpGeneratorDriver(opt, ImmutableArray.Create<ISourceGenerator>(new Class1()), ImmutableArray<AdditionalText>.Empty);
        driver.RunFullGeneration(compilation, out var resultCompilation, out _);
        // ここまで

        return resultCompilation;
    }
}
```

一応これでステップインできそう。

**Comment by ufcpp-live** [comment]
https://youtu.be/aZENYVSEpIY

**Comment by ufcpp-live** [comment]
そしてアナリティクスを見てると…

![image](https://user-images.githubusercontent.com/62176519/80861232-1e5c9600-8ca8-11ea-9379-62f24e845661.png)

今でも https://youtu.be/W5u0GvCPx7Y こいつの再生数100単位であるんか…
