### ISSUE TITLE
VS 17.1 Preview 2

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#50]
配信URL: https://youtu.be/lxr0QlZR0M4

.NET チームもそろそろホリデーから帰ってきたっぽい感じなので配信も再開(2か月ぶり)。

## リリースノート

https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.1.0-pre.2.0

気になるとこ:

* Editor
  * Visual Studio can now automatically save code documents whenever the application loses focus.
    * 個人的にはまじでやめて欲しいんだけど…
    * 保存をトリガーにしてビルド開始しちゃう質の悪い開発ツールがいて、しかもそいつ重たいんで
  * The Code Cleanup feature can now be configured to be run whenever a file is explicitly saved.
    * using の消えすぎとか、改行コード誤混入とかやりそう…
* IDE
  * Added ability to toggle color scheme to color your tabs by File Extension or Project.
    * 前からなかったっけ？ preview はずれた？
* .NET Productivity
  * We now surface Source Link as part of Go to Definition, allowing you to navigate to the original source file.
    * ついに F12 で飛べるように(F11 ステップイン実行は前からできたはず)
  * We added a new Stack Trace Explorer window.

## C# 11

2個ほど実装追加。

### 17.1p1 から

```cs
var a = 1;
var b = 2;
var s = $"a: {
    a // ここの改行
    }, b: {
    b
    }";
```

### 17.1p2 から

```cs
var x = new[] { 1, 2, 3, 4, 5 };

if (x.AsSpan() is [1, .. var y, 5]) // list pattern
{
    foreach (var item in y)
    {
        Console.WriteLine(item);
    }
}
```

**Comment by ufcpp** [comment]
配信なかった間に、配信中に口頭でだけ話したけど文章で残してなかったものを色々ブログ化してたけども…

まだまだネタが残ってたり

![image](https://user-images.githubusercontent.com/3760955/148560907-6d0c2906-d5b2-4685-a045-0bb7d47dc75a.png)

**Comment by ufcpp-live** [comment]
```cs
new[] {1} [0..][0..][0..] is [..[..[1]]]
```

**Comment by ufcpp-live** [comment]
```cs
new int[] {} [..][..][..] is [..[..[]]]
```

**Comment by ufcpp-live** [comment]
```cs
// Visual Studio はこれを怒らない。
// Resharper は double negation 直すか？って聞いてくるらしい。
if (x is not not not not not not not not not not not null)
{
    Console.WriteLine("x is not null");
}
```

**Comment by ufcpp-live** [comment]
多分バグ。
要バグ報告。

![image](https://user-images.githubusercontent.com/62176519/148643938-6820be2e-2d1c-4551-9b2f-7d3a5e6fbac8.png)

```cs
new[] { 1  } is [var x] and x is 1
```

**Comment by ufcpp-live** [comment]
```cs
using System.Text;

var utf8 = Encoding.UTF8.GetBytes("何か").AsSpan();

// BOM を取る
if (utf8 is [0xEF, 0xBB, 0xBF, .. var noBom])
{
    utf8 = noBom;
}
```

**Comment by ufcpp-live** [comment]
```cs
void m(Span<byte> span)
{
    if (span is [var head, .. var tail])
    {
        Console.WriteLine(head);
        if (tail.Length > 0) m(tail);
    }
}
```

**Comment by ufcpp-live** [comment]
辞書パターンも出るの？ (案だけあって、進捗なし)

```cs
// 案はあるけど、リストパターン以上に需要低そう…
// ただ、文法的にはよっぽど素直な予感あり。
var d = new Dictionary<string, string>()
{
    ["abc"] = "one",
};

if (d is { ["abc"] is "one"})
{
}
```

**Comment by ufcpp-live** [comment]
```cs
var d = new Dictionary<string, string>()
{
    { "abc", "one" },
};

// リストパターンが enumerable 対応するならこう書ける？
if (d is [ .., ("abc", "one"), ..])
{
}
```

**Comment by ufcpp-live** [comment]
多分仕様的にダメなんだけど、せめてエラーメッセージもうちょっとまともにしてほしい事案。

```cs
var x = new[,] { { 1, 2 }, { 3, 4 } };

var y = x[^1, ^1]; // これ、元からダメ。

if(x is [[1,..], [_,_]]) // なのでこれもダメな可能性大。
{
}
```

**Comment by ufcpp-live** [comment]
```cs
// rectangular array は元から変。
// 最適化もかかりにくくてあんまり使えない。
var x = new[,] { { 1, 2 }, { 3, 4 } };

Console.WriteLine(x is System.Collections.IEnumerable);
Console.WriteLine(x is IEnumerable<int>);

foreach (var item in x) // パターンベース foreach
{
    Console.WriteLine(item);
}
```

**Comment by ufcpp-live** [comment]
↑特別な人でした。

![image](https://user-images.githubusercontent.com/62176519/148644939-8854068c-4a38-4ae3-936b-8a73b4960cee.png)

**Comment by ufcpp-live** [comment]
```cs
var s = $"{123:X}"; // 条件演算子の : と書式指定の : の区別がつかない

void m(object x)
{
    var s = @$"{( // なのでここ、 () が必須。
        x is int i
        ? i
        : "aaa"
        )}";
}
```

**Comment by ufcpp-live** [comment]
```cs
// C# 10 で improved interpolated string が入ったので、
// {} にいろいろ詰め込むのはメリットなくはない(速い可能性はある)。
// とはいえ、メソッド抽出しろよ。
var s = @$"{( // なのでここ、 () が必須。
    x is int[] a && a is [var i, ..]
    ? i
    : "aaa"
    )}";
```

**Comment by ufcpp-live** [comment]
```cs
// 多分これ書ける interpolated string handler 書けるはず。
// (せめて key: value であったほしいけど無理ｗ)
var s = CreateDictionary($"{x:Key1}{y:Key2}");
```

**Comment by ufcpp-live** [comment]
非匿名
![image](https://user-images.githubusercontent.com/62176519/148646324-53d71bb9-e017-45d3-aaaf-d60ecad6aec1.png)

匿名、アウトー－
![image](https://user-images.githubusercontent.com/62176519/148646330-25b90390-427b-4f1c-8b66-4f3b939757da.png)

**Comment by ufcpp-live** [comment]
Stack Trace Explorer の現状、だいぶ未成熟感ある…
まあまだ preview 2 なので…

例外ダイアログとかに組み込まれてくれたらだいぶ嬉しそう。

**Comment by ufcpp-live** [comment]
「コードクリーンナップの設定がおかしい人がいたのでクリーンナップしておきました。」

**Comment by ufcpp-live** [comment]
![image](https://user-images.githubusercontent.com/62176519/148647122-d9a66e7f-7725-40fa-9f59-8621e90505f1.png)

**Comment by ufcpp-live** [comment]
成人式。

![image](https://user-images.githubusercontent.com/62176519/148647837-2059fb02-2b4a-4d61-8cd6-3eb1317f9c1e.png)
