### ISSUE TITLE
.NET 8 Preview 1 出たら何かやる

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#67]
配信URL: https://youtube.com/live/Kai58qBvaVA
トラッキング用: https://csharp.connpass.com/event/276195/

## (2/22 追記)出た。

* [Announcing .NET 8 Preview 1](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-1/)
* リリース ノート
  * [Visual Studio 17.6 Preview 1](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.6.0-pre.1.0)
  * [Visual Studio 17.5 GA](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.5.0)

`{` の位置がおかしくてなえ気味。

https://developercommunity.visualstudio.com/t/Place-open-brace-settings-are-buggy/10287032?port=1025&fsid=e8019e49-2128-44f2-90ce-a93fc44c9519

## C#

* たぶん、去年の年末か、遅くても先月のpreview3で入ってたっぽいけども、Lambda default parameters 入ってた
* [Length-based switch dispath 入ってそう](https://twitter.com/ufcpp/status/1628358936163393537) (roslyn 66081)

## 事前のメモ

core 8133

* Random.GetItems
* パフォーマンス系のクラス・メソッド追加
  * FrozenDictionary, FrozenSet
  * ImmutableArray の DrainToImmutable
  * IndexOfAnyValues
  * CompositeFormat 
* dotnet publish and dotnet pack produce Release assets by default
* Numerics and Intrinsics
  * AVX-512 命令 
  * Vector512 が、512 ビット intrinsics 使えなくても Vector256 使った実装になってて多少速くなるとのこと
* `<WasmEnableWebcil>true</WasmEnableWebcil>`
  * Blazor Wasm で dll 拡張子ダウンロードしようとしてディフェンダーとかファイアウォールに引っかかる人がいたらしく
  * 引っかからない新形式の .webcil を用意
* System.Text.Json
  * ないメンバー読むときのオプション
  * インターフェイスが階層持ってる時に対応
  * snake_case, kebab-case

**Comment by ufcpp** [comment]
```cs
m("aaa");

static int m(string s) => s switch
{
    "abc" => 1,
    "defg" => 2,
    "hijkl" => 3,
    "mln" => 4,
    "op" => 5,
    "qrst" => 6,
    "uvw" => 7,
    "xy" => 8,
    "z" => 9,
    _ => 0,
};
```

**Comment by ufcpp** [comment]
```cs
using System.Text.Json;
using System.Text.Json.Serialization;

var json = """{ "X": 123, "Y": "abc" }""";

Console.WriteLine(JsonSerializer.Deserialize(json, MyContext.Default.Immutable));
Console.WriteLine(JsonSerializer.Deserialize(json, MyContext.Default.InitProp));
Console.WriteLine(JsonSerializer.Deserialize(json, MyContext.Default.Class));

record class Class(int X, string Y);

readonly partial record struct Immutable(int X, string Y);

readonly partial record struct InitProp
{
    public int X { get; init; }
    public string Y { get; init; }
}

[JsonSerializable(typeof(Class))]
[JsonSerializable(typeof(Immutable))]
[JsonSerializable(typeof(InitProp))]
partial class MyContext : JsonSerializerContext { }
```

deserialize 側はリフレクションっぽい雰囲気感じるコード生成だけどどうなんだろ。
InitProp もなんか InitPropCtorParamInit 生成してる。コンストラクターないのに。

**Comment by ufcpp-live** [comment]
https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md

```xml
<Project>
  <PropertyGroup>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
  </PropertyGroup>
</Project>
```

**Comment by ufcpp-live** [comment]
大体1000ペアで破綻。

![image](https://user-images.githubusercontent.com/62176519/221411400-63186f89-dcaa-4df9-9380-c7b1434abff6.png)
![image](https://user-images.githubusercontent.com/62176519/221411428-a9eb2c9d-1a10-4fe3-a81f-43bed9600c51.png)

**Comment by ufcpp-live** [comment]
```cs
using System.Collections.Frozen;
using System.Text.Json;

var data = new KeyValuePair<string, int>[]
{
    new("one", 1),
    new("two", 2),
    new("three", 3),
};

var frozen = data.ToFrozenDictionary();

// Serialize はいける。
var json = JsonSerializer.Serialize(frozen);

Console.WriteLine(json);

// 直接の Deserialize<FrozenDictionary<string, int>>() は無理
var x = JsonSerializer.Deserialize<Dictionary<string, int>>("""
    {"one":1,"two":2,"three":3}
    """)!.ToFrozenDictionary();
```

**Comment by ufcpp-live** [comment]
```cs
using System.Text;

var config = new
{
    // 外部から読むときは {x} みたいな interpolation 使えない
    MyFooFormat = "{0} = {1}",
};

// いままで or パフォーマンス気にしない
for (int i = 0; i < 1000; i++)
{
    _ = string.Format(config.MyFooFormat, i, 2);
}

// これから、パフォーマンスが必須なら
// 最初に1回手間かける
var format = CompositeFormat.Parse(config.MyFooFormat);
for (int i = 0; i < 1000; i++)
{
    // その後繰り返し使うなら速い
    _ = string.Format(null, format, i, 2);
}
```

**Comment by ufcpp-live** [comment]
```cs
var f = (int x = 1, params int[] y) => Console.WriteLine(x);
A2 f2 = (int x = 1, params int[] y) => Console.WriteLine(x);

f(); // 1
f2(); // 2

Console.WriteLine(f2.Method.GetParameters()[0].DefaultValue); // 1

delegate void A2(int x = 2, params int[] y);
```

**Comment by ufcpp** [comment]
```cs
using System.Reflection;

A a = (int x = 2) => { };

MethodInfo m1 = a.Method;
MethodInfo m2 = a.GetType().GetMethod("Invoke")!;

Console.WriteLine(m1.GetParameters()[0].DefaultValue); // 2
Console.WriteLine(m2.GetParameters()[0].DefaultValue); // 1

delegate void A(int x = 1);
```
