### ISSUE TITLE
【C# 9.0 がやってきた】Build 2020 で .NET 5 Preview 4 公開

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#7]
[Microsoft Build](https://mybuild.microsoft.com/) に合わせていろいろとブログ公開が。

- [Announcing .NET 5 Preview 4 and our journey to one .NET](https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/)
- [Releasing Today! Visual Studio 2019 v16.6 & v16.7 Preview](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-6-and-v16-7-preview-1-ship-today/)
  - [16.6 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.0)
  - [16.7 Preview 1 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.7.0-pre.1.0)
- [Introducing .NET Multi-platform App UI](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/)
- [Windows Forms Designer for .NET Core Released](https://devblogs.microsoft.com/dotnet/windows-forms-designer-for-net-core-released/)
- [Announcing Entity Framework Core 5.0 Preview 4](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-5-0-preview-4/)
- [ML.NET Model Builder is now a part of Visual Studio](https://devblogs.microsoft.com/dotnet/ml-net-model-builder-is-now-a-part-of-visual-studio/)
- [Windows Terminal 1.0](https://devblogs.microsoft.com/commandline/windows-terminal-1-0/)
- [Windows Package Manager Preview](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/)
- [Introducing WinUI 3 Preview 1](https://blogs.windows.com/windowsdeveloper/2020/05/19/introducing-winui-3-preview-1/)
- [The Windows Subsystem for Linux BUILD 2020 Summary](https://devblogs.microsoft.com/commandline/the-windows-subsystem-for-linux-build-2020-summary/)
- [DirectX is coming to the Windows Subsystem for Linux](https://devblogs.microsoft.com/directx/directx-heart-linux/)
- []()
- [Expanding Visual Studio 2019 support for Visual Studio Codespaces](https://devblogs.microsoft.com/visualstudio/expanding-visual-studio-2019-support-for-visual-studio-codespaces/)
- [Live Share, now with chat and audio support!](https://devblogs.microsoft.com/visualstudio/live-share-now-with-chat-and-audio-support/)

正直、ブログ読みふけってて Build のキーノート([ブチザッキ](https://blog.azure.moe/2020/05/20/microsoft-build-2020-keynote%e7%9a%84%e3%81%aa%e4%bd%95%e3%81%8b/)参照)全然聞いてない。

1回の配信で触れる量じゃないし、とりあえずC# 9.0 の話を中心に(他はチャットの反応次第)。

C# 9.0:

- [Language Feature Status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md)
  - native int, target-typed new, pattern V3 の[3つ、動作確認済み](https://gist.github.com/ufcpp/3b0f78de250dc94243bd8015250779b0)
  - pattern は「merged」になってないけど動いてる(変更の可能性ちょっとだけあり)
- [Build の C# Today & Tomorrow デモ](https://mybuild.microsoft.com/sessions/cea64369-aed9-4497-83f1-d3cf1360a57d) では [Records](https://github.com/dotnet/csharplang/issues/39) と [Top-level statements](https://github.com/dotnet/csharplang/blob/master/proposals/top-level-statements.md) も動いてたけどこれは Build 用のブランチみたい
- [16.7.P1 milestone](https://github.com/dotnet/roslyn/milestone/69)
- [sharplab](https://sharplab.io/) には Records ブランチと target-typed conditional ブランチ と Top-level statements ブランチあり

**Comment by ufcpp-live** [comment]
配信中に書き散らかした結果:

```cs
// new features in .NET 5 preview 4

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Runtime.InteropServices.ComTypes;
using System.Threading;

interface IA { int A(); }
interface IB : IA { int B(); }
interface IC : IA { int C(); }

class Ab : IB, IC
{
    public int A() => 2;
    public int B() => 3;
    public int C() => 5;
}

class Program
{
    static void Main()
    {
        Console.WriteLine(float.NaN == float.NaN); //false

        //// native int
        //nint i = 1;
        //nint u = 2;
        //Console.WriteLine(i + u);
    }

    // target-typed new
    static Dictionary<string, int> d = new()
    {
        { "a", 1 },
    };

    static void M1(object obj)
    {
        // !ReferenceEquals(obj, null)
        if (obj is { }) // 知ってないと意味不明
        {
        }
        // 同じ意味
        if (obj is not null) // 初見さんにやさしい
        {
        }

        // ユーザー定義の != があればそれを呼ぶ
        if (obj != null)
        {
        }

        IA a = obj is null
            ? (IA)null
            : (IB)null;

        int b1 = obj is null
            ? (byte)1
            : (int)2;

        int? c1 = obj is null
            ? (int?)null
            : (int)2;

        IA aa = obj switch
        {
            IB b => b,
            IC c => c,
        };

        M((short)1, obj is null ? (int)1 : (short)2);
    }

    static void M(short x, short y) { }
    static void M(int x, int y) { }

    static void M<T>(T obj)
        where T : IB, IC // and
    {
        obj.A();
        obj.B();
        obj.C();
    }

    //static void M<T>(T obj)
    //    where T : IB or IC // 要望はあり。別提案
    //{
    //    obj.A();
    //    obj.B();
    //    obj.C();
    //}

    static int M11(object obj) => obj switch
    {
        byte => 1,
        sbyte => 1,
        ushort => 2,
        short => 2,
        int => 4,
        uint => 4,
        long => 8,
        ulong => 8,
        DateTime => 8,
        DateTimeOffset => 16,
        Guid => 16,
        _ => -1,
    };

    static int M11(bool b) => b switch
    {
        true => 1,
        false => 0,
    };

    class A { }
    class B : A { }
    class C : A { }

#nullable enable
    // pattern V3 (and, or, not, simple type, parenthesized...)
    static int M(object? obj) => obj switch
    {
        IB b and IC c => b.A() * b.B() * c.C(),
        (IA or IB) and var a => a.A(),
        //(B or C) and var a => a.A(), // object です(今のところ)。A にする提案あり
        string s => s.Length,
        //{ } a => a.GetHashCode(), // not null の意味含む(初見に厳しい)
        not null and var a => a.GetHashCode(),
    };

    // pattern V3 (rerational, exhaustivity check)
    static int M(float value) => value switch
    {
        < (10 * 10) => 1,
        >= 100 and < 500 => 2,
        5 * 100 => 5,
        > 500 => 3,
        float.NaN => 4,
        //_ => 2,
    };

    static int M111(float value) => value switch
    {
        var x when x < 100 => 1,
        var x when x >= 100 && x <= 500 => 2,
        var x when x > 500 => 3,
    };

    // pattern V3 (byte exhaustivity check)
    static int M(byte ascii) => ascii switch
    {
        <= 31 => 0, // control
        32 => 2, // white space
        <= 47 => 3, // symbol
        <= 57 => 4, // number
        <= 64 => 3, // symbol
        >= (int)'A' and <= (int)'Z' => 5, // letter A-Z
        >= (int)'a' and <= (int)'z' => 5, // letter a-z
        > (int)'z' and <= 126 => 3,
        127 => 0,
        >= 128 => 6, // non-asci
    };
}
```

**Comment by ufcpp-live** [comment]
https://youtu.be/fZxRZgWYqq0
