### ISSUE TITLE
GitHub Copilot Chat のウェイトリスト通った

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#71]
配信URL: https://youtube.com/live/qCgYFPOA53g?feature=share

使えるようになったのでとりあえず試す配信。

**Comment by ufcpp-live** [comment]
![image](https://github.com/ufcpp-live/UfcppLiveAgenda/assets/62176519/41ad55ba-338f-44fd-9bce-283f9316c0dd)

**Comment by ufcpp-live** [comment]
webアプリにしてください

minimal APIにしてください
