### ISSUE TITLE
.NET 8 Preview 5 & Visual Studio 17.7 Preview 2 & vscode C# Dev Kit

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#73]
配信URL: https://youtube.com/live/M5weHOCzJ6E

* [Announcing .NET 8 Preview 5](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-preview-5/)
* [Visual Studio 2022 17.7 Preview 2 is here!](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-7-preview-2-is-here/)
* [ASP.NET Core updates in .NET 8 Preview 5](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-8-preview-5/)
* [Announcing .NET MAUI in .NET 8 Preview 5](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8-preview-5/)

.NET 8、Code Analisys 系の Analyzer 追加くらいしか個人的に引かれたところなかったりするけども。
VS、F5 実行のスピードアップは気になるけども、20% 改善だとあんまり体感わかんないかも。

ついで:

* [Announcing C# Dev Kit for Visual Studio Code](https://devblogs.microsoft.com/visualstudio/announcing-csharp-dev-kit-for-visual-studio-code/)

**Comment by ufcpp-live** [comment]
```cs
using System.Globalization;
using System.Runtime.CompilerServices;

Console.WriteLine(DateTime.Now);

// source generator で強制的に足せば…
static class Initialier
{
    [ModuleInitializer]
    public static void Init()
    {
        var c = (CultureInfo)CultureInfo.InvariantCulture.Clone();
        c.DateTimeFormat.LongDatePattern = "yyyy'-'MM'-'dd";
        c.DateTimeFormat.LongTimePattern = "HH':'mm':'ss";
        c.DateTimeFormat.MonthDayPattern = "MM'-'dd";
        c.DateTimeFormat.YearMonthPattern = "yyyy'-'MM";
        c.DateTimeFormat.ShortDatePattern = "yyyy'-'MM'-'dd";
        c.DateTimeFormat.ShortTimePattern = "HH':'mm':'ss";

        CultureInfo.DefaultThreadCurrentCulture = c;
    }
}
```

**Comment by ufcpp-live** [comment]
誰よりも後ろに呼ばれてほしい ModuleInitializer は \uffff.cs なファイル名のファイルに書くといいよ！

**Comment by ufcpp-live** [comment]
![image](https://github.com/ufcpp-live/UfcppLiveAgenda/assets/62176519/2a6e1888-08d2-40bb-8be5-81fa3dd3f835)

※ `<InvariantGlobalization>false</InvariantGlobalization>` に限る

**Comment by ufcpp** [comment]
https://gist.github.com/ufcpp/071785157dfb8402af27b443427f8b90
