### ISSUE TITLE
.NET 8 正式リリース記念

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#83]
配信URL: https://www.youtube.com/watch?v=1w-E4QgmAdg

1年振り返る？

リリース関連ブログ等:

* [.NET Conf](https://www.dotnetconf.net/)
  * [.NET Conf 2023 - Day 1](https://www.youtube.com/watch?v=xEFO1sQ2bUc)
* [Announcing .NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/)
* [Announcing C# 12](https://devblogs.microsoft.com/dotnet/announcing-csharp-12/)
* [Visual Studio 17.8 now available!](https://devblogs.microsoft.com/visualstudio/visual-studio-17-8-now-available/)
  * [17.8.0 リリースノート](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.8.0)
* [Introducing Visual Studio 17.9 – Preview 1 is Here!](https://devblogs.microsoft.com/visualstudio/introducing-visual-studio-17-9-preview-1-is-here/)
  * [17.9p1 リリースノート](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#17.9.0-pre.1.0)
* [Announcing ASP.NET Core in .NET 8](https://devblogs.microsoft.com/dotnet/announcing-asp-net-core-in-dotnet-8/)
* [Announcing .NET MAUI in .NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-maui-in-dotnet-8/)
* [Introducing .NET Aspire: Simplifying Cloud-Native Development with .NET 8](https://devblogs.microsoft.com/dotnet/introducing-dotnet-aspire-simplifying-cloud-native-development-with-dotnet-8/)
* []()

## C# 12

今年、割かし「コレクション式とプライマリコンストラクターの2個」感ある。
プライマリコンストラクター相変わらず燃えがち。
小さい機能が今年全然なかったってのあるかも。

コレクション式とプライマリコンストラクターは Visual Studio のサジェスト出てる分くらいは書き換えてもいいかも。
会社で今触ってるコード、それぞれ1000件以上出てた。

## C# 13?

`\e` (エスケープ文字のエスケープシーケンス)、もう入ってた。

## .NET

* IUtf8SpanFormattable, IUtf8SpanParsable
* TimeProvider
* Vector512
* UnsafeAccessor
* ConfigureAwaitOptions
* SearchValues
* FrozenDictionary

個人の感想等

* FrozenDictionary 導入済み
* TimeProvider 全面的に使いたいけども既存コードの DateTimeOffset.Now/UtcNow 直呼びしてるところ多すぎて泣きそう
* IUtf8SpanFormattable, IUtf8SpanParsable だいぶありがたいけども自分で実装する人は少なそう
* UnsafeAccessor 本来用途は AOT でリフレクションの代わりだけど、テストで internal visible to の代わりに使うのの方が熱そう

**Comment by ufcpp-live** [comment]
```cs
using System.Runtime.CompilerServices;

M(null!);

[UnsafeAccessor(UnsafeAccessorKind.StaticMethod, Name = "M")]
static extern void M(in Static _);

// static を付けると困る
class Static
{
    public static void M() { }
}

```

**Comment by ufcpp-live** [comment]
```cs
// 匿名レコードだと思うと X, Y はプロパティに類する。
// 大文字。
(int X, int Y) t;

// 多値戻り値だと思うと x, y は変数に類する。
// 小文字。
(int x, int y) m(int x, int y) => (x, y);
```
