### ISSUE TITLE
【C# 9.0/VS 16.7 preview 2】Source Generator 再来。partial メソッドの仕様拡張

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#9]
https://twitter.com/ufcpp/status/1268886214205046784

![image](https://user-images.githubusercontent.com/3760955/83931728-3492d000-a7d9-11ea-8c10-2de500ec0126.png)

https://twitter.com/ufcpp/status/1268898836749021184

![image](https://user-images.githubusercontent.com/3760955/83931732-39f01a80-a7d9-11ea-967d-fffdde24c060.png)

## 配信中やろうと思ってること

twitter にスクショを上げたものは、Sample ソリューションの Class1.cs にべた書きな状態。
これを「清書」しつつ、Source Generator とか partial メソッドの仕様拡張の話をしようかと。

### C# 9.0: partial メソッドの拡張

[Extending Partial Methods](https://github.com/jaredpar/csharplang/blob/partial/proposals/extending-partial-methods.md)

Visual Studio 16.7 Preview 2 での唯一の追加。

空実装を用意 → Source Generator でメソッド本体を生成できるようになった。

### Source Generator

[以前の配信](https://github.com/ufcpp-live/UfcppLiveAgenda/issues/5) とそんなに変わってなさそう。
前回も説明のベースにした[公式サンプル](https://github.com/dotnet/roslyn-sdk/tree/master/samples/CSharp/SourceGenerators) を見ながら作ってる。

## 作ったものの概要

作った Source Generator は、文字列を UTF-8 な `ReadOnlySpan<byte>` に置き換える処理をしてる。
コンパイル結果的にもちゃんと UTF-8 で保存されて、ASCII 主体なら単純にデータ量が半減する。
UTF-8 を直接扱いたいときに `string` (UTF-16) からの無駄な変換がなくなる利点もあり。

### ReadOnlySpan 最適化

[静的なデータの ReadOnlySpan 最適化](https://ufcpp.net/blog/2018/12/staticdatareadonlyspan/)

これを使ってる。
ソースコード上 `new byte[]` してるけど、アロケーションは掛からない。

### Utf8String? UTF-8 リテラル?

.NET に `Utf8String` を追加しようって話はこじれ気味？

- `Span<byte>` に対する UTF-8 操作である程度満足してそう
- `string` の中身自体を UTF-8 にしたいという要望もあって、これと `Utf8String` 型が競合してる
- .NET 5 世代は「Xamarin との統合」全振りで、他に大きな作業はあんまりできない

で、C# に UTF-8 リテラルが入るとすると…

[LDM Sept. 16, 2019](https://github.com/dotnet/csharplang/blob/master/meetings/2019/LDM-2019-09-16.md)

> Current proposal is to emit the data as UTF-16, and use a runtime helper to project to UTF-8.

初期実装では、コンパイル結果にはいったん UTF-16 で記録(現状の `string` リテラルの実装を使う)した上で、実行時に UTF-8 への変換を掛ける提案になってる。
もちろん効率悪い。あとから高効率な実装に差し替える想定。

UTF-8 リテラル自体 C# 9.0 からは漏れそうな上に初期実装がこれなので。
「自前 UTF-8 リテラルもどき Source Generator」の需要は最低でも2・3年はあると思う。
(早々に需要なくなってほしいけど、残念ながら)

**Comment by ufcpp** [comment]
正直、↓ が許されると黒魔術のやりがいが増すんだけど…

```cs
using System.Diagnostics.CodeAnalysis;

class Program
{
    // 属性中の nameof から引数名を参照できるようにしたいという話あり。
    // (外にも s がいる時に破壊的変更にならないようにするのが面倒)
    [NotNullIfNotNull(nameof(s))]
    void M(string s) { }

    static void Main()
    {
        // string interpolation 中に const string しかないとき、$"" 全体を const 扱いしたいという話あり。
        const string s = $"{"aaa"}";
    }
}
```

どっちも優先度低そう？

**Comment by ufcpp** [comment]
MemberNotNull, MemberNotNullWhen も preview 2 で入ってそう。

**Comment by ufcpp-live** [comment]
配信中出た話

バグ:

```cs
partial class C
{
    public static partial int M();
}

partial class C
{
    public static partial void M() { }
}

class Program
{
    static void Main()
    {
        _ = C.M();
    }
}
```

もしかしたら要求なくはないかも:

```cs
partial class C : I
{
    partial void I.M(); // 欲しい！
}

partial class C : I
{
    partial void I.M() { }
}
```

**Comment by ufcpp-live** [comment]
https://youtu.be/1Ic2VN3I5vI

**Comment by ufcpp-live** [comment]
名称候補:

リポジトリ名: StringLiteralGenerator
generator の名前空間: StringLiteralGenerator
generator 名: Utf8StringLiteralGenerator
属性: StringLiteral.Utf8
