### ISSUE TITLE
.NET 9 GA 記念

### ISSUE THREAD

**Issue by ufcpp** [ufcpp-live/UfcppLiveAgenda#97]
配信URL: https://www.youtube.com/live/4uQUB-98RaU

RC 2からの変更がそんなに多いわけなく、「GA を祝う会」的な。
時間の残り方によっては https://github.com/ufcpp-live/UfcppLiveAgenda/issues/96 の続きやる。

公式アナウンス

* [Announcing .NET 9](https://devblogs.microsoft.com/dotnet/announcing-dotnet-9/)
* announcements 332 (.NET 8 からの差分の What's new の一覧)
  * [What's new in .NET 9](https://learn.microsoft.com/ja-jp/dotnet/core/whats-new/dotnet-9/overview)
  * [runtime](https://learn.microsoft.com/ja-jp/dotnet/core/whats-new/dotnet-9/runtime)
  * [libraries ](https://learn.microsoft.com/ja-jp/dotnet/core/whats-new/dotnet-9/libraries)
  * [sdk](https://learn.microsoft.com/ja-jp/dotnet/core/whats-new/dotnet-9/sdk)
    * `--allow-roll-forward` とか絶対要る
  * [C#](https://learn.microsoft.com/ja-jp/dotnet/csharp/whats-new/csharp-13)
    * [こいつだけ ja-jp の内容が古い](https://x.com/ufcpp/status/1856488533730701729)
    * 他は「翻訳されてない部分は英語だけど、情報落ちはない」状態
  * [ASP.NET](https://learn.microsoft.com/ja-jp/aspnet/core/release-notes/aspnetcore-9.0?view=aspnetcore-9.0)
  * [Aspire](https://learn.microsoft.com/ja-jp/dotnet/aspire/whats-new/)
  * [MAUI](https://learn.microsoft.com/ja-jp/dotnet/maui/whats-new/dotnet-9?view=net-maui-9.0)
  * [EF](https://learn.microsoft.com/ja-jp/ef/core/what-is-new/ef-core-9.0/whatsnew)
  * [WPF](https://learn.microsoft.com/ja-jp/dotnet/desktop/wpf/whats-new/net90?view=netdesktop-9.0)
  * [WinForms](https://learn.microsoft.com/ja-jp/dotnet/desktop/winforms/whats-new/net90?view=netdesktop-9.0)
* API diff
  * between .NET 9 RC2 and .NET 9 GA: core 9601
  * between .NET 8 and .NET 9: core 9602
* Visual Studio release notes
  * [17.12](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.12.0)
  * [17.13 Preview 1](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview?tabs=allfeatures#17.13.0-pre.1.0)
    * (.editorconfig ないときの)ファイルのエンコード指定できるように
    * Ctrl + , で最近開いたファイル見れるように
    * Feature Search に Copilot
    * テーマを変えてもフォント設定残るように

## API ちょっと差分あった

![image](https://github.com/user-attachments/assets/c96e724d-f2a2-450d-8216-64f91ab70e4e)

runtime 108537 が削除 PR。

* インスタンスメソッドなので優先度高くて既存の拡張メソッドを隠す
* 挙動は既存の拡張メソッドと違う(やばい)

受ける。

## First-class Span

GA 早々、Preview (14 で正式に入る予定)の機能が1個 merge。
https://github.com/ufcpp/UfcppSample/issues/479

## その他、最近の csharplang

`nameof(T<>)` (open generic を使えるように)、Working Set 入りして Pull Request 出てる。

Extensions、再始動していろいろアイディア出してたらまたコメント白熱気味。

**Comment by ufcpp-live** [comment]
一応、 int.MinValue はビット表現的に特殊ではある。


// sbyte x = -128; // sbyte.MinValue
// 0x80
// var y = -x; // ~x + 1;
// ~0x80 + 1 = 0x7F + 1 = 0x80

**Comment by ufcpp-live** [comment]
```cs
C? x = null;

if (x is { } c)
    if (c.B is { } b)
        if (b.A is { } a) a.X += 1;

//これを、こうじゃ

x?.B?.A?.X += 1; // こうしたいってのが null conditional assingment
// short-circuit 付きなので、途中で null だったら右辺の評価はされないはず。

// なんとなく、(x?.B?.A?.X) += 1 っぽく見えて、null += 1 っぽく見える…

// ++x?.B?.A?.X は不可。
// つられて x?.B?.A?.X++ も不可。

class A { public int X { get; set; } }
class B { public A? A { get; set; } }
class C { public B? B { get; set; } }
```

**Comment by ufcpp-live** [comment]
ClassLibrary1:

```cs
namespace ClassLibrary1;

public interface I
{
    protected private static abstract void M();
}

public class X<T> where T : I;
```

ConsoleApp1:

```cs
using ClassLibrary1;

var s = nameof(X<>);
Console.WriteLine(s); // "X"

interface Dummy : I
{
}
```

**Comment by ufcpp-live** [comment]
```cs
A? a = null;

if (a == null) return;

Console.WriteLine(a.X); // ここ来ちゃう上に、ここでぬるぽ。

// 回避策、is 使え。
if (a is null) return; // Unity さんはこいつに警告出す。
// (A が UnityEngine.GameObject 派生の場合だけ。)

class A
{
    public int X;

    public static bool operator ==(A? x, A? y) => false;
    public static bool operator !=(A? x, A? y) => false;
}
```

**Comment by ufcpp-live** [comment]
```cs
var a = nameof(Span<>); // System.Span にしてほしいことがまれになくはない。

// 提案1:
// rejected か backlog かだった気はする。
var a1 = fullnameof(Span<>);

// 提案2:
// 最近 rejected。
var a2 = typeof(Span<>).FullName; // これを (JIT 時じゃなく、コンパイラーの) const 扱いにしたい。
```

**Comment by ufcpp-live** [comment]
C# エディターUIの制御文字バグと、Copilot さんの応答。

![image](https://github.com/user-attachments/assets/08567b69-9498-41b3-91ba-5553f7e11833)
